export const BaumArtLatIds = {
  1: {
    1: "domestica (Apfel-Obstgeh\u00f6lz 'Spartan')",
    2: "domestica (Apfel-Obstgeh\u00f6lz 'Heimenhofer')",
    3: "domestica (Apfel-Obstgeh\u00f6lz 'Reanda')",
    4: "domestica (Apfel-Obstgeh\u00f6lz 'Schneiderapfel')",
    5: "domestica (Apfel-Obstgeh\u00f6lz 'Topaz')",
    6: "domestica (Apfel-Obstgeh\u00f6lz 'Hordapfel')",
    7: "domestica (Apfel-Obstgeh\u00f6lz 'Bohnapfel')",
    8: "domestica (Apfel-Obstgeh\u00f6lz 'D\u00fcbendorfer Milchapfel')",
    9: "domestica (Apfel-Obstgeh\u00f6lz 'Wissapfel H\u00f6ri')",
    10: "domestica (Apfel-Obstgeh\u00f6lz 'Leuenapfel')",
    11: "domestica (Apfel-Obstgeh\u00f6lz 'Oberrieder Glanz-Renette')",
    12: "domestica (Apfel-Obstgeh\u00f6lz 'Schweizer Breitacher')",
    13: "domestica (Apfel-Obstgeh\u00f6lz 'Brettacher Gew\u00fcrzapfel')",
    14: "domestica (Apfel-Obstgeh\u00f6lz 'Witiker Chuechliapfel')",
    15: "domestica (Apfel-Obstgeh\u00f6lz 'W\u00e4denswiler Rosenapfel')",
    16: "domestica (Apfel-Obstgeh\u00f6lz 'Hansueli')",
    17: "domestica (Apfel-Obstgeh\u00f6lz 'Beffert')",
    18: "domestica (Apfel-Obstgeh\u00f6lz 'Hauxapfel')",
    19: "domestica (Apfel-Obstgeh\u00f6lz 'Z\u00fcriapfel')",
    20: "domestica (Apfel-Obstgeh\u00f6lz 'St\u00e4fner Rosen')",
    21: "domestica (Apfel-Obstgeh\u00f6lz 'Glockenapfel')",
    22: "domestica (Apfel-Obstgeh\u00f6lz 'Thurgauer Weinapfel')",
    23: 'domestica (Apfel-Obstgeh\u00f6lz, Sorte unbekannt)',
    24: "domestica (Apfel-Obstgeh\u00f6lz 'Klarapfel')",
    25: "domestica (Apfel-Obstgeh\u00f6lz 'Schweizer Orangenapfel')",
    26: "domestica (Apfel-Obstgeh\u00f6lz 'Boskoop')",
    27: "domestica (Apfel-Obstgeh\u00f6lz 'Berlepsch rot')",
    28: "domestica (Apfel-Obstgeh\u00f6lz 'Jacques Lebel')",
    29: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00fcssgrauech')",
    30: "domestica (Apfel-Obstgeh\u00f6lz 'Iduna')",
    31: "domestica (Apfel-Obstgeh\u00f6lz 'Sauergrauech')",
    32: "domestica (Apfel-Obstgeh\u00f6lz 'Gravensteiner')",
    33: "domestica (Apfel-Obstgeh\u00f6lz 'Blauacher W\u00e4denswil')",
    34: "domestica (Apfel-Obstgeh\u00f6lz 'Usterapfel')",
    35: "domestica (Apfel-Obstgeh\u00f6lz 'Sch\u00f6ner von Boskoop')",
    36: "domestica (Apfel-Obstgeh\u00f6lz 'Ariwa')",
    37: 'spec. (Zier-Apfel, Art unbekannt)',
    38: "domestica (Apfel-Obstgeh\u00f6lz 'Jonathan')",
    39: "domestica (Apfel-Obstgeh\u00f6lz 'Sauergrauch')",
    40: "domestica (Apfel-Obstgeh\u00f6lz 'Remo')",
    41: "domestica (Apfel-Obstgeh\u00f6lz 'Jonagold')",
    42: 'domestica (Apfel-Obstgeh\u00f6lz)',
    43: 'domestica (Apfel-Obstgeh\u00f6lz, Rondo)',
    44: "domestica (Apfel-Obstgeh\u00f6lz 'L\u00f6hningerrosen')",
    45: "domestica (Apfel-Obstgeh\u00f6lz 'Zeienapfel der Ostschweiz')",
    46: "domestica (Apfel-Obstgeh\u00f6lz 'Sch\u00f6ner von Nordhausen')",
    47: "domestica (Apfel-Obstgeh\u00f6lz 'Ontario')",
    48: "domestica (Apfel-Obstgeh\u00f6lz 'King of the Pippins' (Goldparm\u00e4ne))",
    49: "domestica (Apfel-Obstgeh\u00f6lz 'Ananas Reinette')",
    50: "domestica (Apfel-Obstgeh\u00f6lz 'Z\u00fcrcher Transparent')",
    51: "domestica (Apfel-Obstgeh\u00f6lz 'Berner Rosenapfel')",
    52: "domestica (Apfel-Obstgeh\u00f6lz 'Galiwa')",
    53: "domestica (Apfel-Obstgeh\u00f6lz 'Goldrenette Freiherr von Berlepsch' (Berlepsch))",
    54: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Gravensteiner')",
    55: "domestica (Apfel-Obstgeh\u00f6lz 'Gloster' (Gloster 69))",
    56: 'trilobata (Dreilappiger Apfel)',
    57: "domestica (Apfel-Obstgeh\u00f6lz 'Ladina')",
    58: 'floribunda (Zier-Apfel)',
    59: "domestica (Apfel-Obstgeh\u00f6lz 'Florina' (Querina))",
    60: "domestica (Apfel-Obstgeh\u00f6lz 'Boskoop-Schmitz-H\u00fcbsch')",
    61: "domestica (Apfel-Obstgeh\u00f6lz 'Aargauer Herrenapfel')",
    62: "domestica (Apfel-Obstgeh\u00f6lz 'Rubinola')",
    63: 'null (Zier-Apfel)',
    64: "domestica (Apfel-Obstgeh\u00f6lz 'Brauner Boskoop')",
    65: "domestica (Apfel-Obstgeh\u00f6lz 'Rode Boskoop'-Schmitz-H\u00fcbsch)",
    66: "domestica (Apfel-Obstgeh\u00f6lz 'Maigold')",
    67: "domestica (Apfel-Obstgeh\u00f6lz 'Idared')",
    68: "domestica (Apfel-Obstgeh\u00f6lz 'Mira')",
    69: "domestica (Apfel-Obstgeh\u00f6lz 'Retina')",
    70: "domestica (Apfel-Obstgeh\u00f6lz 'Transparent de Croncels')",
    71: "domestica (Apfel-Obstgeh\u00f6lz 'Minister von Hammerstein')",
    72: "domestica (Apfel-Obstgeh\u00f6lz 'Goldstar')",
    73: "domestica (Apfel-Obstgeh\u00f6lz 'Gala')",
    74: "domestica (Apfel-Obstgeh\u00f6lz 'Aargauer Jubil\u00e4umsapfel')",
    75: "domestica (Apfel-Obstgeh\u00f6lz 'Otava')",
    76: 'sylvestris (Holzapfelbaum)',
    77: "domestica (Apfel-Obstgeh\u00f6lz 'Goro')",
    78: "domestica (Apfel-Obstgeh\u00f6lz 'Sterappel' (Rote Sternrenette))",
    79: "domestica (Apfel-Obstgeh\u00f6lz 'Prime Rouge')",
    80: "domestica (Apfel-Obstgeh\u00f6lz 'Ametyst')",
    81: 'tschonoskii (Woll-Apfel)',
    82: "domestica (Apfel-Obstgeh\u00f6lz 'Gravensteiner Rellstab')",
    83: "domestica (Apfel-Obstgeh\u00f6lz 'Edelchr\u00fcsler')",
    84: "domestica (Apfel-Obstgeh\u00f6lz 'Wehntaler Hagapfel')",
    85: "domestica (Apfel-Obstgeh\u00f6lz 'Golden Delicious')",
    86: "domestica (Apfelbaum 'Bonita')",
    87: "domestica (Apfel-Obstgeh\u00f6lz 'Resi')",
    88: "domestica (Apfel-Obstgeh\u00f6lz 'Viktoria')",
    89: "domestica (Apfel-Obstgeh\u00f6lz 'Hana')",
    90: "domestica (Apfel-Obstgeh\u00f6lz 'Rewena')",
    91: "domestica (Apfel-Obstgeh\u00f6lz 'Prinzenapfel')",
    92: "domestica (Apfel-Obstgeh\u00f6lz 'Rajka')",
    93: "domestica (Apfel-Obstgeh\u00f6lz 'Liberty')",
    94: "domestica (Apfel-Obstgeh\u00f6lz 'Pfirsichroter Sommerapfel')",
    95: "domestica (Apfel-Obstgeh\u00f6lz 'Alant')",
    96: 'domestica (Apfel-Obstgeh\u00f6lz \'K\u00f6niginapfel "The Queen" \')',
    97: "domestica (Apfel-Obstgeh\u00f6lz 'Goldparm\u00e4ne')",
    98: "domestica (Apfel-Obstgeh\u00f6lz 'Tobi\u00e4ssler')",
    99: "domestica (Apfel-Obstgeh\u00f6lz 'Aargauer J\u00e4gerapfel')",
    100: "domestica (Apfel-Obstgeh\u00f6lz 'Grauer Hordapfel')",
    101: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Boskoop')",
    102: "domestica (Apfel-Obstgeh\u00f6lz 'Champagner Reinette')",
    103: "domestica (Apfel-Obstgeh\u00f6lz 'Goldreinette von Blenheim')",
    104: "domestica (Apfel-Obstgeh\u00f6lz 'Oetwiler Reinette')",
    105: "domestica (Apfel-Obstgeh\u00f6lz 'Melrose')",
    106: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00fcsser Pfaffenapfel')",
    107: "domestica (Apfel-Obstgeh\u00f6lz 'Gew\u00fcrzluiken')",
    108: "domestica (Apfel-Obstgeh\u00f6lz 'Winterzitrone')",
    109: "domestica (Apfel-Obstgeh\u00f6lz 'Wiederkehr')",
    110: "domestica (Apfel-Obstgeh\u00f6lz 'Z\u00fcrcher Schmutzapfel')",
    111: "domestica (Apfel-Obstgeh\u00f6lz 'Grijze Rabouwe')",
    112: "domestica (Apfel-Obstgeh\u00f6lz 'Sternapi')",
    113: "domestica (Apfel-Obstgeh\u00f6lz 'Dantziger Kantapfel')",
    114: "domestica (Apfel-Obstgeh\u00f6lz 'Breitacher')",
    115: "domestica (Apfel-Obstgeh\u00f6lz 'Bittenfelder')",
    116: "domestica (Apfel-Obstgeh\u00f6lz 'Suregger')",
    117: "domestica (Apfel-Obstgeh\u00f6lz 'Oberl\u00e4nder Himbeerapfel')",
    118: "domestica (Apfel-Obstgeh\u00f6lz 'Gala Galaxy')",
    119: "domestica (Apfel-Obstgeh\u00f6lz 'Kanada Reinette')",
    120: "domestica (Apfel-Obstgeh\u00f6lz 'Ohio Reinette')",
    121: "domestica (Apfel-Obstgeh\u00f6lz 'Elstar')",
    122: "domestica (Apfel-Obstgeh\u00f6lz 'La Flaboyante')",
    123: "domestica (Apfel-Obstgeh\u00f6lz 'Pfaffenapfel')",
    124: "domestica (Apfel-Obstgeh\u00f6lz 'Seidenapfel')",
    125: "domestica (Apfel-Obstgeh\u00f6lz 'Piros')",
    126: "domestica (Apfel-Obstgeh\u00f6lz 'Rafzubin' (Rubinette))",
    127: "domestica (Apfel-Obstgeh\u00f6lz 'Virginischer Rosenapfel')",
    128: "domestica (Apfel-Obstgeh\u00f6lz 'Adersleber Kalvill')",
    129: "domestica (Apfel-Obstgeh\u00f6lz 'Lobo')",
    130: "domestica (Apfel-Obstgeh\u00f6lz 'Vista Bella')",
    131: "domestica (Apfel-Obstgeh\u00f6lz 'Schneica' (Jonica))",
    132: "domestica (Apfel-Obstgeh\u00f6lz 'Mutterapfel')",
    133: "domestica (Apfel-Obstgeh\u00f6lz 'Peasgood's Nonsuch' (Peasgoods Sondergleichen))",
    134: "domestica (Apfel-Obstgeh\u00f6lz 'Edelgrauech')",
    135: "domestica (Apfel-Obstgeh\u00f6lz 'Seel\u00e4nder Reinette')",
    136: "domestica (Apfel-Obstgeh\u00f6lz 'McIntosh')",
    137: "domestica (Apfel-Obstgeh\u00f6lz 'Karmeliterrenette')",
    138: "domestica (Apfel-Obstgeh\u00f6lz 'Himbeerapfel')",
    139: "domestica (Apfel-Obstgeh\u00f6lz 'Bismarkapfel')",
    140: "domestica (Apfel-Obstgeh\u00f6lz 'Baumann's Reinette')",
    141: "domestica (Apfel-Obstgeh\u00f6lz 'Baschiapfel')",
    142: "domestica (Apfel-Obstgeh\u00f6lz 'Ch\u00fcsenreiner')",
    143: "domestica (Apfel-Obstgeh\u00f6lz 'Sir Prize')",
    144: "domestica (Apfel-Obstgeh\u00f6lz 'Franz\u00f6sische Reinette')",
    145: "domestica (Apfel-Obstgeh\u00f6lz 'Kupferreinette')",
    146: "domestica (Apfel-Obstgeh\u00f6lz 'Delcorf' (Delbard Estivale))",
    147: "domestica (Apfel-Obstgeh\u00f6lz 'Dalili' (Ambassy))",
    148: "domestica (Apfel-Obstgeh\u00f6lz 'Julyred')",
    149: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Damason')",
    150: "domestica (Apfel-Obstgeh\u00f6lz 'James Grieve')",
    151: "domestica (Apfel-Obstgeh\u00f6lz 'Wintergrauech')",
    152: "domestica (Apfel-Obstgeh\u00f6lz 'Breno Apfel')",
    153: "domestica (Apfel-Obstgeh\u00f6lz 'Signe Tillisch')",
    154: "domestica (Apfel-Obstgeh\u00f6lz 'Muttergruss')",
    155: "domestica (Apfel-Obstgeh\u00f6lz 'Marmorapfel')",
    156: "domestica (Apfel-Obstgeh\u00f6lz 'Eierlederapfel')",
    157: "domestica (Apfel-Obstgeh\u00f6lz 'Biesterfelder Renette')",
    158: "domestica (Apfel-Obstgeh\u00f6lz 'L\u00e4dericher')",
    159: "domestica (Apfel-Obstgeh\u00f6lz 'Begginger Glocken')",
    160: "domestica (Apfel-Obstgeh\u00f6lz 'Kronen Reinette')",
    161: "domestica (Apfel-Obstgeh\u00f6lz 'R\u00fcdlinger Weissapfel')",
    162: "domestica (Apfel-Obstgeh\u00f6lz 'Cilander')",
    163: "domestica (Apfel-Obstgeh\u00f6lz 'B\u00f6lleapfel')",
    164: "domestica (Apfel-Obstgeh\u00f6lz 'Sonnenapfel')",
    165: "domestica (Apfel-Obstgeh\u00f6lz 'Gelber Richard')",
    166: "domestica (Apfel-Obstgeh\u00f6lz 'Gruniker')",
    167: "domestica (Apfel-Obstgeh\u00f6lz 'Guntalinger')",
    168: "domestica (Apfel-Obstgeh\u00f6lz 'Fraurotacher')",
    169: "domestica (Apfel-Obstgeh\u00f6lz 'Sch\u00f6napfel')",
    170: "domestica (Apfel-Obstgeh\u00f6lz 'Sch\u00f6ner aus Bath')",
    171: "domestica (Apfel-Obstgeh\u00f6lz 'Zitronenreinette')",
    172: "domestica (Apfel-Obstgeh\u00f6lz 'Kr\u00fcgers Dickstiel')",
    173: "domestica (Apfel-Obstgeh\u00f6lz 'Spitzwissiker')",
    174: "domestica (Apfel-Obstgeh\u00f6lz 'Arlet')",
    175: "domestica (Apfel-Obstgeh\u00f6lz 'Lord Grosvenor')",
    176: "domestica (Apfel-Obstgeh\u00f6lz 'The Queen (La Reine)')",
    177: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00fcsser Basler (Maiapfel)')",
    178: "domestica (Apfel-Obstgeh\u00f6lz 'Adams Parm\u00e4ne')",
    179: "domestica (Apfel-Obstgeh\u00f6lz 'Oregon')",
    180: "domestica (Apfel-Obstgeh\u00f6lz 'Geflammter Kardinal')",
    181: "domestica (Apfel-Obstgeh\u00f6lz 'Renora')",
    182: "domestica (Apfel-Obstgeh\u00f6lz 'Br\u00fcnnerling')",
    183: "domestica (Apfel-Obstgeh\u00f6lz 'Schmutzapfel')",
    184: "domestica (Apfel-Obstgeh\u00f6lz 'Torb\u00e4chler')",
    185: "domestica (Apfel-Obstgeh\u00f6lz 'Rouge de Juvigny')",
    186: "domestica (Apfel-Obstgeh\u00f6lz 'Birnf\u00f6rmiger Apfel')",
    187: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Sauergrauech')",
    188: "domestica (Apfel-Obstgeh\u00f6lz 'B\u00e4nziger')",
    189: "domestica (Apfel-Obstgeh\u00f6lz 'Melchnauer')",
    190: "domestica (Apfel-Obstgeh\u00f6lz 'Gallway Pepping')",
    191: "domestica (Apfel-Obstgeh\u00f6lz 'Wiener Reinette')",
    192: "domestica (Apfel-Obstgeh\u00f6lz 'Chestnut')",
    193: "domestica (Apfel-Obstgeh\u00f6lz 'F\u00e4llander Milchapfel')",
    194: "domestica (Apfel-Obstgeh\u00f6lz 'Nela')",
    195: "domestica (Apfel-Obstgeh\u00f6lz 'Wildmuser')",
    196: "domestica (Apfel-Obstgeh\u00f6lz 'Rhapsodie')",
    197: "domestica (Apfel-Obstgeh\u00f6lz 'Spindellino')",
    198: "domestica (Apfel-Obstgeh\u00f6lz 'Sonate')",
    199: "domestica (Apfel-Obstgeh\u00f6lz 'Habermehler')",
    200: "domestica (Apfel-Obstgeh\u00f6lz 'Damason Reinette')",
    201: "domestica (Apfel-Obstgeh\u00f6lz 'B\u00fchler Erdbeerapfel')",
    202: "domestica (Apfel-Obstgeh\u00f6lz 'N\u00fcssler Apfel')",
    203: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Sprunzler')",
    204: "domestica (Apfel-Obstgeh\u00f6lz 'Engelsberger Renette')",
    205: "domestica (Apfel-Obstgeh\u00f6lz 'Cox's Orange')",
    206: "domestica (Apfel-Obstgeh\u00f6lz 'Api \u00e8toil\u00e9e')",
    207: "domestica (Apfel-Obstgeh\u00f6lz 'Alkmene')",
    208: "domestica (Apfel-Obstgeh\u00f6lz 'Jamba 69')",
    209: "domestica (Apfel-Obstgeh\u00f6lz 'Weisser Konstanzer')",
    210: "domestica (Apfel-Obstgeh\u00f6lz 'Weisser Basler Wintertafet')",
    211: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Winterkalvill')",
    212: "domestica (Apfel-Obstgeh\u00f6lz 'Rafzer Weissapfel')",
    213: "domestica (Apfel-Obstgeh\u00f6lz 'Zimts\u00fcss')",
    214: "domestica (Apfel-Obstgeh\u00f6lz 'Plume')",
    215: "domestica (Apfel-Obstgeh\u00f6lz 'Puppenapfel')",
    216: "domestica (Apfel-Obstgeh\u00f6lz 'Onegin')",
    217: "domestica (Apfel-Obstgeh\u00f6lz 'Olpogen Reinette')",
    218: "domestica (Apfel-Obstgeh\u00f6lz 'Ognam')",
    219: "domestica (Apfel-Obstgeh\u00f6lz 'Mupler')",
    220: "domestica (Apfel-Obstgeh\u00f6lz 'Prinz Albrecht von Preussen')",
    221: "domestica (Apfel-Obstgeh\u00f6lz 'Schoggiapfel')",
    222: "domestica (Apfel-Obstgeh\u00f6lz 'Lord Lambourne')",
    223: "domestica (Apfel-Obstgeh\u00f6lz 'Maling von Kent')",
    224: "domestica (Apfel-Obstgeh\u00f6lz 'Ochsenstirne')",
    225: "domestica (Apfel-Obstgeh\u00f6lz 'Opulatio')",
    226: "domestica (Apfel-Obstgeh\u00f6lz 'Jestetterli')",
    227: "domestica (Apfel-Obstgeh\u00f6lz 'Knuchler')",
    228: "domestica (Apfel-Obstgeh\u00f6lz 'Mantet')",
    229: "domestica (Apfel-Obstgeh\u00f6lz 'M\u00f6ringerrosen')",
    230: "domestica (Apfel-Obstgeh\u00f6lz 'Pilot')",
    231: "domestica (Apfel-Obstgeh\u00f6lz 'Kidd's Orange')",
    232: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00fcsser Verenacher')",
    233: "domestica (Apfel-Obstgeh\u00f6lz 'Clusius')",
    234: "domestica (Apfel-Obstgeh\u00f6lz 'Weberapfel')",
    235: "domestica (Apfel-Obstgeh\u00f6lz 'Caddel')",
    236: "domestica (Apfel-Obstgeh\u00f6lz 'Pupille')",
    237: "domestica (Apfel-Obstgeh\u00f6lz 'Civni' (Rubens))",
    238: "domestica (Apfel-Obstgeh\u00f6lz 'Otlinger')",
    239: "domestica (Apfel-Obstgeh\u00f6lz 'Saurer Pfaffenapfel')",
    240: "domestica (Apfel-Obstgeh\u00f6lz 'Schmelzling')",
    241: "domestica (Apfel-Obstgeh\u00f6lz 'Sultivan')",
    242: "domestica (Apfel-Obstgeh\u00f6lz 'Siblinger Fraurotacher')",
    243: "domestica (Apfel-Obstgeh\u00f6lz 'Schmutzecher')",
    244: "domestica (Apfel-Obstgeh\u00f6lz 'Ungarischer Rosmarin')",
    245: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00fcssler')",
    246: "domestica (Apfel-Obstgeh\u00f6lz 'Triangel')",
    247: "domestica (Apfel-Obstgeh\u00f6lz 'Zuccalmaglio')",
    248: "domestica (Apfel-Obstgeh\u00f6lz 'Herbst-Reinette Eschenz')",
    249: "domestica (Apfel-Obstgeh\u00f6lz 'Horub Wattwil')",
    250: "domestica (Apfel-Obstgeh\u00f6lz 'Wyssegger')",
    251: "domestica (Apfel-Obstgeh\u00f6lz 'Hallauer Maienapfel')",
    252: "domestica (Apfel-Obstgeh\u00f6lz 'Gulborg')",
    253: "domestica (Apfel-Obstgeh\u00f6lz 'Grundigapfel')",
    254: "domestica (Apfel-Obstgeh\u00f6lz 'Haagreinette')",
    255: "domestica (Apfel-Obstgeh\u00f6lz 'Stina Lohmann')",
    256: "domestica (Apfel-Obstgeh\u00f6lz 'Gisiapfel')",
    257: "domestica (Apfel-Obstgeh\u00f6lz 'Grawehr Reinette')",
    258: "domestica (Apfel-Obstgeh\u00f6lz 'Sommerzitrone')",
    259: "domestica (Apfel-Obstgeh\u00f6lz 'Domino')",
    260: "domestica (Apfel-Obstgeh\u00f6lz 'Pinova')",
    261: 'domestica (Apfel-Obstgeh\u00f6lz, Ballerina)',
    262: 'toringo (Japan-Apfel)',
    263: "domestica (Apfel-Obstgeh\u00f6lz 'Borstorfer')",
    264: "domestica (Apfel-Obstgeh\u00f6lz 'K\u00f6niglicher Kurzstiel')",
    265: "domestica (Apfel-Obstgeh\u00f6lz 'Versailles')",
    266: "domestica (Apfel-Obstgeh\u00f6lz 'Menznauer J\u00e4ger')",
    267: "domestica (Apfel-Obstgeh\u00f6lz 'Opal')",
    268: 'domestica (Apfelbaum)',
    269: "domestica (Apfel-Obstgeh\u00f6lz 'Galloway')",
    270: 'domestica (Apfel-Obstgeh\u00f6lz, Rosana)',
    271: 'domestica (Apfel-Obstbaumgeh\u00f6lz, Rubinette)',
    272: 'prunifolia (Kirsch-Apfel)',
    273: "domestica (Apfel-Obstgeh\u00f6lz 'Weisser Basler')",
    274: "domestica (Apfel-Obstgeh\u00f6lz 'Weisser Wintertaffetapfel')",
    275: "domestica (Apfel-Obstgeh\u00f6lz 'Muskat Reinette')",
    276: "domestica (Apfel-Obstgeh\u00f6lz 'Holstein')",
    277: 'pumila (Zier-Apfel)',
    278: "domestica (Apfel-Obstgeh\u00f6lz 'Empire')",
    279: 'x purpurea (Zier-Apfel)',
    280: "domestica (Apfel-Obstgeh\u00f6lz 'Thurgauer Borsdorfer')",
    281: "domestica (Apfel-Obstgeh\u00f6lz 'Reinette Damason')",
    282: "domestica (Apfel-Obstgeh\u00f6lz 'Dulcessa')",
    283: "domestica (Apfel-Obstgeh\u00f6lz 'Golden Reinders')",
    284: "domestica (Apfel-Obstgeh\u00f6lz 'Red Topaz')",
    285: "domestica (Apfel-Obstgeh\u00f6lz 'Moonlight')",
    286: "domestica (Apfel-Obstgeh\u00f6lz 'Indierfrog')",
    287: "domestica (Apfel-Obstgeh\u00f6lz 'Alter Berner Rosen')",
    288: "domestica (Apfel-Obstgeh\u00f6lz 'Braeburn')",
    289: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00fcssholz')",
    290: "domestica (Apfel-Obstgeh\u00f6lz 'S\u00f6dliapfel')",
    291: "domestica (Apfel-Obstgeh\u00f6lz 'Franz\u00f6sische Goldrenette')",
    292: "domestica (Apfel-Obstgeh\u00f6lz 'Goldpepping')",
    293: "domestica (Apfel-Obstgeh\u00f6lz 'Buh\u00f6lzler')",
    294: "domestica (Apfel-Obstgeh\u00f6lz 'Edmond Iwan')",
    295: "domestica (Apfel-Obstgeh\u00f6lz 'Bedfotdshire')",
    296: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Astrachan')",
    297: "domestica (Apfel-Obstgeh\u00f6lz 'Summerred')",
    298: "domestica (Apfelbaum 'Regine')",
    299: "domestica (Apfel-Obstgeh\u00f6lz, 'Rotfleischiger 91.1')",
    300: "domestica (Apfel-Obstgeh\u00f6lz, 'Spitzlederapfel')",
    301: "domestica (Apfel-Obstgeh\u00f6lz 'Sp\u00e4tlauber')",
    302: "domestica (Apfel-Obstgeh\u00f6lz 'Jonathan Watson')",
    303: "domestica (Apfel-Obstgeh\u00f6lz 'Wilerrot')",
    304: "domestica (Apfel-Obstgeh\u00f6lz 'Osnabr\u00fccker Reinette')",
    305: "domestica (Apfel-Obstgeh\u00f6lz 'Sch\u00f6ner von Kent')",
    306: "domestica (Apfel-Obstgeh\u00f6lz 'Kasseler Renette')",
    307: "domestica (Apfel-Obstgeh\u00f6lz 'Br\u00fcnerling (Typ Roter Stettiner)')",
    308: "domestica (Apfel-Obstgeh\u00f6lz 'Roter Berlepsch')",
    309: "domestica (Apfel-Obstgeh\u00f6lz 'Bramley's Seedling')",
    310: "domestica (Apfel-Obstgeh\u00f6lz 'Ecolette')",
  },
  2: {
    311: "communis (Birne-Obstgeh\u00f6lz 'Goldschmeckler')",
    312: "communis (Birne-Obstgeh\u00f6lz 'Wagner Wildbirne')",
    313: 'communis (Birne-Obstgeh\u00f6lz, Sorte unbekannt)',
    314: "communis (Birne-Obstgeh\u00f6lz 'Conference')",
    315: "communis (Birne-Obstgeh\u00f6lz 'Knollbirne')",
    316: "communis (Birne-Obstgeh\u00f6lz 'Melonenbirne')",
    317: "communis (Birne-Obstgeh\u00f6lz 'Kuhbirne')",
    318: "communis (Birne-Obstgeh\u00f6lz 'Winter Nelis')",
    319: 'communis (Gemeiner Birnbaum)',
    320: "communis (Birne-Obstgeh\u00f6lz 'Doyenn\u00e9 du Comice')",
    321: "communis (Birne-Obstgeh\u00f6lz 'Schweizer Wasserbirne')",
    322: "communis (Birne-Obstgeh\u00f6lz 'Z\u00fcrcher Zuckerbirne')",
    323: "communis (Birne-Obstgeh\u00f6lz 'Williams Christbirne')",
    324: "communis (Birne-Obstgeh\u00f6lz 'Palmischbirne')",
    325: "communis (Gemeiner Birnbaum 'Wilde Eierbirne')",
    326: "communis (Birne-Obstgeh\u00f6lz 'Welschbergler')",
    327: "communis (Birne-Obstgeh\u00f6lz 'Reinholzbirne')",
    328: "communis (Birne-Obstgeh\u00f6lz 'Ottenbacher Schellerbirne')",
    329: "communis (Birne-Obstgeh\u00f6lz 'Champagner Bratbirne')",
    330: "communis (Birne-Obstgeh\u00f6lz 'Herbstg\u00fcetler')",
    331: "communis (Birne-Obstgeh\u00f6lz 'Chatzengrind')",
    332: "communis (Birne-Obstgeh\u00f6lz 'Sch\u00f6ne Helene')",
    333: "communis (Birne-Obstgeh\u00f6lz 'Wasserbirne')",
    334: "communis (Birne-Obstgeh\u00f6lz 'Gute Luise')",
    335: "communis (Birne-Obstgeh\u00f6lz 'Edelcrassane')",
    336: "communis (Birne-Obstgeh\u00f6lz 'Directeur Hardy')",
    337: 'calleryana (Chinesische Wild-Birne, Stadt-Birne)',
    338: 'salicifolia (Weidenbl\u00e4ttrige Birne)',
    339: 'calleryana (Chinesische Wild-Birne)',
    340: "communis (Birne-Obstgeh\u00f6lz 'Herzogin Elsa')",
    341: "communis (Birne-Obstgeh\u00f6lz 'Gute Graue')",
    342: "communis (Birne-Obstgeh\u00f6lz 'Goldb\u00e4chler')",
    343: "communis (Birne-Obstgeh\u00f6lz 'H\u00fcngler')",
    344: "communis (Birne-Obstgeh\u00f6lz 'Bayrische Weinbirne')",
    345: "communis (Birne-Obstgeh\u00f6lz 'Giffards Butterbirne')",
    346: "communis (Birne-Obstgeh\u00f6lz 'Pierre Corneille')",
    347: "communis (Birnen-Obstgeh\u00f6lz 'Karcherbirne')",
    348: "communis (Birne-Obstgeh\u00f6lz 'Harrow Sweet')",
    349: "communis (Birne-Obstgeh\u00f6lz 'Sch\u00fcrbirne')",
    350: "communis (Birnen-Obstgeh\u00f6lz 'Walsche Schnapsbirne')",
    351: "communis (Birne-Obstgeh\u00f6lz 'Esperence Herrenbirne')",
    352: "communis (Birne-Obstgeh\u00f6lz 'Doppelte Phillips Birne')",
    353: "communis (Birne-Obstgeh\u00f6lz 'Rafzas' (Benita))",
    354: "communis (Birne-Obstgeh\u00f6lz 'Schmelzende von Thirriot')",
    355: "communis (Birne-Obstgeh\u00f6lz 'K\u00f6stliche von Charneux')",
    356: "communis (Birne-Obstgeh\u00f6lz 'Pastorenbirne')",
    357: "communis (Birne-Obstgeh\u00f6lz 'Comtesse de Paris')",
    358: "communis (Birne-Obstgeh\u00f6lz 'Clapp's Favourite')",
    359: "communis (Birne-Obstgeh\u00f6lz 'Beurr\u00e9 Bosc' (Kaiser Alexander))",
    360: "communis (Birne-Obstgeh\u00f6lz 'Gr\u00fcnm\u00f6stler')",
    361: "communis (Birne-Obstgeh\u00f6lz 'Gelbm\u00f6stler')",
    362: "communis (Birne-Obstgeh\u00f6lz 'Egnacher Mostbirne')",
    363: "communis (Birne-Obstgeh\u00f6lz 'Schweizerhose')",
    364: 'spec. (Zier-Birne, Art unbekannt)',
    365: "communis (Birne-Obstgeh\u00f6lz 'Clairgeaus Butterbirne')",
    366: "communis (Birne-Obstgeh\u00f6lz 'Sept en Gueule')",
    367: "communis (Birne-Obstgeh\u00f6lz 'Marxenbirne')",
    368: "communis (Birne-Obstgeh\u00f6lz 'Uta')",
    369: "communis (Birne-Obstgeh\u00f6lz 'Eierbirne')",
    370: "communis (Birne-Obstgeh\u00f6lz 'Schwarzr\u00e4dler')",
    371: "communis (Birne-Obstgeh\u00f6lz 'Metzer Bratbirne')",
    372: "communis (Gemeiner Birnbaum 'Grosser Katzenkopf')",
    373: "communis (Birne-Obstgeh\u00f6lz 'B\u00e4riker')",
    374: "communis (Birne-Obstgeh\u00f6lz 'Madame Verte')",
    375: "communis (Birne-Obstgeh\u00f6lz 'Notaire Lepin')",
    376: "communis (Birne-Obstgeh\u00f6lz 'Kifferbirne')",
    377: "communis (Birne-Obstgeh\u00f6lz 'Nordh\u00e4user Forellenbirne')",
    378: "communis (Birne-Obstgeh\u00f6lz 'Packham's Triumph')",
    379: "communis (Gemeiner Birnbaum 'President Roosevelt')",
    380: "communis (Gemeiner Birnbaum 'Hardenponts Winterbutterbirne')",
    381: "communis (Birne-Obstgeh\u00f6lz 'Beurr\u00e9 Hardy' (Gellerts Butterbirne))",
    382: "communis (Birne-Obstgeh\u00f6lz 'Fr\u00fche Morettini')",
    383: "communis (Birne-Obstgeh\u00f6lz 'Triomphe de Vienne')",
    384: "communis (Birne-Obstgeh\u00f6lz 'Blumbachs Butterbirne')",
    385: "communis (Birne-Obstgeh\u00f6lz 'Ober\u00f6sterreicher Weinbirne')",
    386: "communis (Birne-Obstgeh\u00f6lz 'Kiefferbirne')",
    387: "communis (Birne-Obstgeh\u00f6lz 'Rote Williams')",
    388: "communis (Birne-Obstgeh\u00f6lz 'Stuttgarter Geisshirtle')",
    389: "communis (Birne-Obstgeh\u00f6lz 'Beurr\u00e9 Diel')",
    390: "communis (Birne-Obstgeh\u00f6lz 'Andenken an den Kongress')",
    391: "communis (Birne-Obstgeh\u00f6lz 'Dr Jules Guyot')",
    392: "communis (Birne-Obstgeh\u00f6lz 'Bunte Julibirne')",
    393: "communis (Birne-Obstgeh\u00f6lz 'Wettinger Holzbirne')",
    394: "communis (Birne-Obstgeh\u00f6lz 'Abb\u00e9 F\u00e9tel')",
    395: "communis (Birne-Obstgeh\u00f6lz 'Theilersbirne')",
    396: "communis (Birne-Obstgeh\u00f6lz 'G\u00e9n\u00e9ral Leclerc')",
    397: "communis (Birne-Obstgeh\u00f6lz 'Schweizer Bratbirne')",
    398: "communis (Birne-Obstgeh\u00f6lz 'Paradiesbirne')",
    399: "communis (Birne-Obstgeh\u00f6lz 'Obelisk')",
    400: "communis (Birne-Obstgeh\u00f6lz 'Rousselet d?Hiver')",
    401: "communis (Birne-Obstgeh\u00f6lz 'Schafbirne')",
    402: 'communis (Palabirne)',
    403: "communis (Birne-Obstgeh\u00f6lz 'Williams Christ')",
    404: "pyrifolia (Nashi-Birne-Obstgeh\u00f6lz 'Kosui')",
    405: "pyrifolia (Nashi-Birne-Obstgeh\u00f6lz 'Chojuro')",
    406: "pyrifolia (Nashi-Birne-Obstgeh\u00f6lz 'Nijisseiki')",
    407: "communis (Birne-Obstgeh\u00f6lz 'Decora')",
    408: "communis (Birne-Obstgeh\u00f6lz 'Weinbirne')",
    409: "communis (Birne-Obstgeh\u00f6lz 'Beurr\u00e9 Giffard')",
    410: "communis (Birne-Obstgeh\u00f6lz 'Bergamot d'Esperen')",
    411: "communis (Birne-Obstgeh\u00f6lz 'Regentin')",
    412: "communis (Birne-Obstgeh\u00f6lz 'Nonpareille Bergamotte')",
    413: "communis (Birne-Obstgeh\u00f6lz 'Condora')",
    414: "communis (Birne-Obstgeh\u00f6lz 'Schoggibirne')",
    415: "communis (Birne-Obstgeh\u00f6lz 'Tr\u00fcbler')",
    416: "communis (Birne-Obstgeh\u00f6lz 'Beurr\u00e9 Alexandre Lucas')",
    417: 'x canescens (Graubl\u00e4ttrige Birne)',
    418: "communis (Birne-Obstgeh\u00f6lz 'Beurr\u00e9 d'Anjou')",
    419: "communis (Birne-Obstgeh\u00f6lz 'Happerswiler')",
    420: "communis (Birne-Obstgeh\u00f6lz 'Affeltr\u00e4ngler')",
    421: "communis (Birne-Obstgeh\u00f6lz 'Herbstl\u00e4ngler')",
    422: "communis (Birne-Obstgeh\u00f6lz 'B\u00fcschelibirne')",
    423: "communis (Birne-Obstgeh\u00f6lz 'Kannenbirne')",
    424: "communis (Birne-Obstgeh\u00f6lz 'Wildling von Sargans')",
    425: "communis (Birne-Obstgeh\u00f6lz 'Z\u00fcribirne')",
    426: "communis (Birne-Obstgeh\u00f6lz 'H\u00e4uffler')",
    427: "communis (Birne-Obstgeh\u00f6lz 'Kirschenbirne')",
    428: "communis (Birne-Obstgeh\u00f6lz 'Rosalettibirne')",
    429: "communis (Birne-Obstgeh\u00f6lz 'Schweizer Mehlbirne')",
    430: "communis (Birne-Obstgeh\u00f6lz 'S\u00fclibirne')",
    431: "communis (Birne-Obstgeh\u00f6lz 'Egnacher Spitzbirne')",
    432: "communis (Birne-Obstgeh\u00f6lz 'Rousselet von Reims')",
    433: "communis (Birne-Obstgeh\u00f6lz 'Gr\u00fcnschibler')",
    434: "communis (Birne-Obstgeh\u00f6lz 'Berner Dornbirne')",
    435: "communis (Birne-Obstgeh\u00f6lz 'Ledisbirne')",
    436: "communis (Birne-Obstgeh\u00f6lz 'Blutbirne Magden')",
    437: "communis (Birne-Obstgeh\u00f6lz 'Julidechantsbirne')",
    438: "communis (Birne-Obstgeh\u00f6lz 'Martin sec panach\u00e9e')",
    439: "communis (Birne-Obstgeh\u00f6lz 'Doyenn\u00e9 Boussoch')",
    440: "communis (Birne-Obstgeh\u00f6lz 'Rotl\u00e4ngler')",
    441: "communis (Birne-Obstgeh\u00f6lz 'Sp\u00e4te Weinbirne')",
    442: "communis (Birne-Obstgeh\u00f6lz 'Zuger R\u00f6teler')",
    443: "communis (Birne-Obstgeh\u00f6lz 'Rotholzbirne')",
    444: "communis (Birne-Obstgeh\u00f6lz 'Neue Poiteau')",
    445: "communis (Birne-Obstgeh\u00f6lz 'Deutsche Nationalbergamotte')",
    446: "communis (Birne-Obstgeh\u00f6lz 'Landsknechtler')",
    447: "communis (Birne-Obstgeh\u00f6lz 'Doppeltragende Muskateller')",
    448: "communis (Birne-Obstgeh\u00f6lz 'Waldersh\u00fcsler')",
    449: "communis (Birne-Obstgeh\u00f6lz 'Schutzibirne')",
    450: "communis (Birne-Obstgeh\u00f6lz 'Kollersbirne')",
    451: "communis (Birne-Obstgeh\u00f6lz 'Madame Favre')",
    452: "communis (Birne-Obstgeh\u00f6lz 'Uelibirne')",
    453: "communis (Birne-Obstgeh\u00f6lz 'Luzeiner L\u00e4nger')",
    454: "communis (Birne-Obstgeh\u00f6lz 'La France / Speckbirne')",
    455: "communis (Birne-Obstgeh\u00f6lz 'Kupplerbirne')",
    456: "communis (Birne-Obstgeh\u00f6lz 'Kalchb\u00fchler')",
    457: 'communis (Birne-Obstgeh\u00f6lz Paulsbirne)',
  },
  3: {
    458: 'regia (Walnuss-Obstgeh\u00f6lz, Sorte unbekannt)',
    459: 'regia (S) (Walnuss-Obstgeh\u00f6lz (S\u00e4mling))',
    460: "regia (Walnuss-Obstgeh\u00f6lz 'Rote Donaunuss')",
    461: "regia (Walnuss-Obstgeh\u00f6lz 'Thunsteller Traubennuss')",
    462: 'regia (Walnuss-Obstgeh\u00f6lz (rotes Blatt))',
    463: "regia (Walnuss-Obstgeh\u00f6lz 'Grafenried')",
    464: "regia (Walnuss-Obstgeh\u00f6lz 'Uhwiesen')",
    465: 'regia (Walnuss-Obstgeh\u00f6lz, Horgen)',
    466: "regia (Walnuss-Obstgeh\u00f6lz 'Hefenhofen')",
    467: "regia (Walnuss-Obstgeh\u00f6lz 'Gansingen')",
    468: "regia (Walnuss-Obstgeh\u00f6lz 'Igis Forst')",
    469: "regia (Walnuss-Obstgeh\u00f6lz 'Dettighofen')",
    470: "regia (Walnuss-Obstgeh\u00f6lz 'Altb\u00fcron')",
    471: "regia (Walnuss-Obstgeh\u00f6lz 'Hinterforst')",
    472: "regia (Walnuss-Obstgeh\u00f6lz 'B\u00f6zberg')",
    473: "regia (Walnuss-Obstgeh\u00f6lz 'Wirz')",
    474: "regia (Walnuss-Obstgeh\u00f6lz 'Franquette')",
    475: "regia (Walnuss-Obstgeh\u00f6lz 'Meylannaise')",
    476: 'regia (Walnuss-Obstgeh\u00f6lz, Benken)',
    477: "regia (Walnuss-Obstgeh\u00f6lz 'Schwamendingen')",
    478: 'nigra (Schwarznuss)',
    479: 'spec. (Walnuss, Art unbekannt)',
    480: "regia (Walnuss-Obstgeh\u00f6lz 'Geisenheim 120')",
    481: "regia (Walnuss-Obstgeh\u00f6lz 'Geisenheim')",
    482: 'ailantifolia (Herzfr\u00fcchtige Walnuss)',
    483: "regia (Walnuss-Obstgeh\u00f6lz 'Rafzer D\u00fcnnschalige')",
    484: "regia (Walnuss-Obstgeh\u00f6lz 'Geisenheim 26')",
    485: 'microcarpa (Felsennuss)',
    486: "regia (Walnuss-Obstgeh\u00f6lz Fernor')",
    487: "regia (Walnuss-Obstgeh\u00f6lz 'Parisienne')",
    488: "regia (Walnuss-Obstgeh\u00f6lz 'Visniscervony' (Juglans regia 'Visniscervony'))",
    489: "regia (Walnuss-Obstgeh\u00f6lz 'Riese von Root' (Juglans regia 'Riese von Root'))",
    490: "regia (Walnuss-Obstgeh\u00f6lz 'Feracker' (Juglans regia 'Feracker'))",
    491: "regia (Walnuss-Obstgeh\u00f6lz 'Winter von Reiten' (Juglans regia 'Winter von Reiten'))",
    492: "regia (Walnuss-Obstgeh\u00f6lz 'Kugel von Triengen' (Juglans regia 'Kugel von Triengen'))",
    493: "regia (Walnuss-Obstgeh\u00f6lz 'Perustinski')",
    494: 'regia (Echte Walnuss)',
    495: "regia (Walnuss-Obstgeh\u00f6lz 'Buccaneer')",
    496: 'mandshurica (Mandschurische Walnuss)',
    497: "regia (Walnuss-Obstgeh\u00f6lz 'Mayette')",
    498: 'ailantifolia (Japanische Walnuss)',
    499: "regia (Walnuss-Obstgeh\u00f6lz 'Hartley')",
    500: "regia (Walnuss-Obstgeh\u00f6lz 'Silvenski')",
    501: "regia (Walnuss-Obstgeh\u00f6lz 'Rote Gubler')",
    502: "regia (Walnuss-Obstgeh\u00f6lz 'Silistrenski')",
    503: "regia (Walnuss-Obstgeh\u00f6lz 'Izvor 10')",
    504: "regia (Walnuss-Obstgh\u00f6lz 'Noyer Rouge')",
    505: "regia (Walnuss-Obstgeh\u00f6lz 'Aufhauser Baden')",
    506: 'regia (Walnuss-Obstgeh\u00f6lz, Dinhard)',
    507: "regia (Walnuss-Obstgeh\u00f6lz 'Milotai 10')",
    508: "regia (Walnuss-Obstgeh\u00f6lz 'Ziegelbr\u00fccke')",
    509: "regia (Walnuss-Obstgeh\u00f6lz 'T83')",
    510: "regia (Walnuss-Obstgeh\u00f6lz 'T2')",
    511: "nigra (Schwarznuss 'Laciniata')",
    512: "regia (Walnuss-Obstgeh\u00f6lz 'Bijou')",
    513: "regia (Walnuss-Obstgeh\u00f6lz 'Dryanovski')",
    514: "regia (Walnuss-Obstgeh\u00f6lz 'Igis-Birkholz')",
    515: "regia (Walnuss-Obstgeh\u00f6lz 'Feradam')",
    516: 'cinerea (Butternuss)',
    517: "regia (Walnuss-Obstgeh\u00f6lz 'Geisenheim 139')",
    518: "regia (Walnuss-Obstgeh\u00f6lz, 'Saturn')",
  },
  4: {
    519: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'B\u00fchler Fr\u00fchzwetschge')",
    520: 'domestica domestica (Zwetschge-Obstgeh\u00f6lz, Sorte unbekannt)',
    521: 'avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz, Sorte unbekannt)',
    522: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Elena')",
    523: 'avium (Vogel-Kirsche, S\u00fcss-Kirsche)',
    524: 'domestica insititia (Pflaume-Obstgeh\u00f6lz, Sorte unbekannt (Pflaume))',
    525: 'domestica (Sammelbegriff f\u00fcr Zwetschgen, Pflaume, Reneklode usw. (Sorte unbek.))',
    526: 'serrulata (Japanische Bl\u00fcten-Kirsche)',
    527: 'padus (Trauben-Kirsche, Faulbaum)',
    528: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'L\u00f6hrpflaume')",
    529: 'domestica syriaca (Pflaume-Obstgeh\u00f6lz, Sorte unbekannt (Mirabelle))',
    530: 'cerasus (Sauer-Kirsche-Obstgeh\u00f6lz, Sorte unbekannt)',
    531: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Hauszwetschge')",
    532: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Tegera')",
    533: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Fellenberg')",
    534: "domestica syriaca (Pflaume-Obstgeh\u00f6lz 'Mirabelle de Nancy')",
    535: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Felsina')",
    536: "domestica syriaca (Pflaume-Obstgeh\u00f6lz 'Mirabelle von Flotow')",
    537: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Kordia')",
    538: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Heidegger')",
    539: 'spec. (Kirsche, Art unbekannt)',
    540: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Hauszwetschge Basel')",
    541: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Herman')",
    542: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Cacanska Lepotica' (Cacaks Sch\u00f6ne))",
    543: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Fellenberg G\u00e4ssli')",
    544: "domestica italica (Pflaume-Obstgeh\u00f6lz 'Grosse Gr\u00fcne Reneklode')",
    545: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Fellenberg FAW 2')",
    546: 'persica (Pfirsich-Obstgeh\u00f6lz, Sorte unbekannt)',
    547: 'null (Zier-Kirsche)',
    548: 'avium (Vogel-Kirsche, S\u00fcss-Kirsche (gef\u00fcllte))',
    549: 'serrulata (Japanische Bl\u00fcten-Kirsche, Japanische Nelken-Kirsche)',
    550: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Regina')",
    551: "domestica (Pflaume-Obstgeh\u00f6lz 'Elena')",
    552: "domestica (Pflaume-Obstgeh\u00f6lz 'Hanita')",
    553: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Ariel')",
    554: 'sargentii (Berg-Kirsche, Sachalin-Kirsche)',
    555: 'sargentii (Scharlach-Kirsche Charles Sargent)',
    556: 'x yedoensis (Yoshino-Kirsche)',
    557: 'spinosa (Schlehe, Schwarzdorn)',
    558: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Auerbacher')",
    559: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Dabrowice')",
    560: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Monarch')",
    561: 'serotina (Sp\u00e4te Traubenkirsche)',
    562: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Ersinger Fr\u00fchzwetschge')",
    563: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Basler Langstieler')",
    564: 'armeniaca (Aprikose-Obstgeh\u00f6lz, Sorte unbekannt)',
    565: 'cerasifera (Kirschpflaume)',
    566: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Bigarreau Hatif Burlat')",
    567: "domestica (Pflaume-Obstgeh\u00f6lz 'Sch\u00f6nberger')",
    568: 'x subhirtella (Higan-Kirsche)',
    569: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Kirkespflaume')",
    570: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Webers Kirsche')",
    571: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Magda')",
    572: 'mahaleb (Stein-Weichsel)',
    573: 'lusitanica (Portugiesische Lorbeer-Kirsche)',
    574: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Dolleseppler')",
    575: "cerasus (Sauer-Kirsche-Obstgeh\u00f6lz 'Hallauer Aemli')",
    576: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Katinka')",
    577: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Techlovan')",
    578: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Lapins')",
    579: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Hanita')",
    580: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Basler Adlerkirsche')",
    581: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Schneider's Sp\u00e4te Knorpelkirsche')",
    582: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Hedelfinger Riesenkirsche')",
    583: 'maackii (Amur-Traubenkirsche)',
    584: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Belle de Paris')",
    585: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Pfirsichpflaume')",
    586: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Valor')",
    587: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Adriana')",
    588: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Giorgia')",
    589: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Octavia')",
    590: "cerasus (Sauer-Kirsche-Obstgeh\u00f6lz 'K\u00f6r\u00f6ser Weichsel')",
    591: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'W\u00f6lflisteiner')",
    592: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Star')",
    593: 'domestica italica (Pflaume-Obstgeh\u00f6lz, Sorte unbekannt (Reneklode))',
    594: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Schauenburger')",
    595: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Rivedel' (Earlise))",
    596: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Kaukasische Riesenkirsche')",
    597: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Grosse Prinzessinkirsche')",
    598: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Weisse Herzkirsche')",
    599: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Alfa')",
    600: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Fr\u00fche Luxemburger')",
    601: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Dattelzwetschge')",
    602: 'avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz)',
    603: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Hauszwetschge Rinklin')",
    604: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Beta')",
    605: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Ruth Gerstetter')",
    606: "domestica (Pflaume-Obstgeh\u00f6lz 'K\u00f6nigin Viktoria')",
    607: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Gelbe Paloge')",
    608: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Zimmers Fr\u00fchzwetschge')",
    609: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Early Laxton')",
    610: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Eierpflaume')",
    611: "domestica italica (Pflaume-Obstgeh\u00f6lz 'Reineclaude d'Oullins')",
    612: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Rafzer Zwetschge')",
    613: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Valjevka')",
    614: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'The Czar')",
    615: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Ortenauer')",
    616: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Wangenheimer Fr\u00fchzwetschge')",
    617: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Sch\u00f6ne von L\u00f6wen')",
    618: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'President')",
    619: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Zopfkirsche')",
    620: "domestica syriaca (Pflaume-Obstgeh\u00f6lz 'Mirabelle von Metz')",
    621: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Geburtstagspflaume')",
    622: "domestica (Pflaume-Obstgeh\u00f6lz 'Hauszwetschge Rinklin')",
    623: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Bachkirsche')",
    624: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Samet')",
    625: 'domestica (Spilling, Haferpflaume, Kirschpflaume)',
    626: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'St\u00e4fner Zwetschge')",
    627: 'dulcis (Mandelbaum-Obstgeh\u00f6lz, Sorte unbekannt)',
    628: 'serrulata (Rotbl\u00e4ttrige Japanische Zierkirsche)',
    629: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Rote Herrenpflaume')",
    630: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Colora')",
    631: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Ontariopflaume')",
    632: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Basler Eierpflaume')",
    633: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Muscat de Debrecen')",
    634: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Opal')",
    635: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Damassine')",
    636: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Golden Japonaise')",
    637: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Langnauer Pflaume')",
    638: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'B\u00e9rudge')",
    639: "domestica syriaca (Pflaume-Obstgeh\u00f6lz 'Zwetschgenfarbige Mirabelle')",
    640: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Rote Lauper')",
    641: "armeniaca (Aprikose-Obstgeh\u00f6lz 'Holub's Zuckeraprikose')",
    642: 'x schmittii (Schmitts-Kirsche)',
    643: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Tophit')",
    644: 'serrula (Tibetanische Kirsche, Mahagoni-Kirsche)',
    645: 'x blireana (gef\u00fclltbl\u00fchende Kirschpflaume)',
    646: "domestica (Pflaume-Obstgeh\u00f6lz 'Dattelpflaume')",
    647: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Alkavo')",
    648: 'pendula (Higan-Kirsche)',
    649: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Eggerzwetschge)",
    650: "cerasus (Sauer-Kirsche-Obstgeh\u00f6lz 'Morello' (Schattenmorelle))",
    651: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Pruntop')",
    652: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Sylvia')",
    653: 'nigra (Kanadische Pflaume, Bitter-Kirsche)',
    654: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Rote Herzkirsche')",
    655: "armeniaca (Aprikose-Obstgeh\u00f6lz 'Goldrich Intel')",
    656: "domestica (Pflaume-Obstgeh\u00f6lz 'Hauszwetschge Rudin')",
    657: "persica (Pfirsich-Obstgeh\u00f6lz 'Alexander')",
    658: 'virginiana (Virginische Traubenkirsche)',
    659: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Rorschacher S\u00fcssweichsel')",
    660: "armeniaca (Aprikose-Obstgeh\u00f6lz 'Luizet')",
    661: "persica (Pfirsich-Obstgeh\u00f6lz 'Redhaven')",
    662: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Cacaks')",
    663: 'padus (Traubenkirsche)',
    664: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Kriechenpflaume')",
    665: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Lauerzer (Rigikirsche)')",
    666: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Presenta')",
    667: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Summit')",
    668: "armeniaca (Aprikose-Obstgeh\u00f6lz 'Aprikose Fantasme')",
    669: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Herzkirsche')",
    670: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Stella')",
    671: 'null (Japanische Bl\u00fcten-Kirsche)',
    672: 'mume (Japanische Aprikose)',
    673: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Grace Star' (Prunus avium 'Grace Star'))",
    674: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'B\u00fclacher Zwetschge')",
    675: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Gamma')",
    676: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Winiger')",
    677: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Rosmarie')",
    678: 'fruticosa (Steppen-Kirsche)',
    679: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Valerij Chkatov')",
    680: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Gerema')",
    681: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Opal')",
    682: "persica (Pfirsich-Obstgeh\u00f6lz 'Revita')",
    683: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Jojo')",
    684: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Cacanska Najbolja' (Cacaks Beste))",
    685: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Cacanska Rodna' (Cacaks Fruchtbare))",
    686: "avium (Vogel-Kirsche, S\u00fcss-Kirsche 'Hartmannsjoggeli')",
    687: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Italiener')",
    688: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Holderbanker')",
    689: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Spitzb\u00fchler (Rot)')",
    690: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Hudson')",
    691: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Chindbettikirsche')",
    692: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Streifenkirsche')",
    693: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Baschimeiri')",
    694: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Gravium')",
    695: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'T\u00e4gertschkirsche')",
    696: "avium (S\u00fcss-Kirsche-Obstgeh\u00f6lz 'Sp\u00e4te Holinger')",
    697: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Schwabs Fr\u00fchzwetschge')",
    698: "domestica domestica (Zwetschge-Obstgeh\u00f6lz 'Chrudimer')",
    699: "domestica insititia (Pflaume-Obstgeh\u00f6lz 'Blaue Eierpflaume')",
  },
  5: {
    700: 'robur (Stiel-Eiche)',
    701: 'spec. (Eiche, Art unbekannt)',
    702: 'rubra (Amerikanische Rot-Eiche)',
    703: 'macrocarpa (Klettenfr\u00fcchtige Eiche)',
    704: 'robur (Stiel-Eiche, s\u00e4ulenf\u00f6rmig)',
    705: 'cerris (Zerr-Eiche)',
    706: 'petraea (Trauben-Eiche)',
    707: 'frainetto (Ungarische Eiche)',
    708: 'macranthera (Persische Eiche)',
    709: 'alba (Weiss-Eiche)',
    710: 'palustris (Sumpf-Eiche)',
    711: 'dentata (Japanische Kaiser-Eiche)',
    712: 'pubescens (Flaum-Eiche)',
    713: 'x turneri (Wintergr\u00fcne Eiche)',
    714: "robur (S\u00e4ulen-Stief-Eiche (Quercus robur 'Fastigiata Zealand'))",
    715: 'prinoides (Chinquapin-Eiche, Zwergkastanien-Eiche)',
    716: 'pyrenaica (Pyren\u00e4en-Eiche)',
    717: 'ilex (Stein-Eiche (immergr\u00fcn))',
    718: 'castaneifolia (Kastanienbl\u00e4ttrige Eiche)',
    719: 'pontica (Armenische Eiche)',
    720: 'bicolor (Sumpf Weiss-Eiche)',
    721: 'ithaburensis (Vallonen Eiche)',
    722: 'null (Trauben-Eiche)',
    723: 'imbricaria (Schindel-Eiche)',
    724: 'x hispanica (Spanische Eiche)',
    725: 'velutina (F\u00e4rber-Eiche)',
    726: 'coccinea (Scharlach-Eiche)',
    727: 'rhysophylla (Monterry-Eiche (immergr\u00fcn))',
    728: 'phellos (Weiden-Eiche)',
    729: 'faginea (Portugiesische Eiche)',
    730: 'acutissima (Seidenraupen-Eiche)',
    731: 'garryana (Oregon Eiche)',
  },
  6: {
    732: 'excelsior (Gemeine Esche)',
    733: 'pennsylvanica (Gr\u00fcn-Esche)',
    734: 'angustifolia (Schmalbl\u00e4ttrige Esche)',
    735: 'ornus (Blumen-Esche, Manna-Esche)',
    736: 'pennsylvanica (Rot-Esche)',
    737: 'latifolia (Oregon-Esche)',
    738: 'pennsylvanica (Gr\u00fcn-Esche, Rot-Esche)',
    739: 'excelsior (Einbl\u00e4ttrige Esche)',
    740: 'spec. (Esche, Art unbekannt)',
    741: 'excelsior (Strassen-Esche)',
    742: 'anomala (Einbl\u00e4ttrige Esche)',
    743: 'americana (Weiss-Esche)',
    744: 'americana (Nussbaumbl\u00e4ttrige Weiss-Esche)',
  },
  7: {
    745: 'glutinosa (Schwarz-Erle, Rot-Erle)',
    746: 'incana (Grau-Erle, Weiss-Erle)',
    747: 'cordata (Italienische-Erle)',
    748: 'spec. (Erle, Art unbekannt)',
    749: 'incana (Grau-Erle, Weiss-Erle (schlitzbl\u00e4ttrig))',
    750: 'glutinosa (Schwarz-Erle, Rot-Erle (schlitzbl\u00e4ttrig))',
    751: 'x spaethii (Purpur-Erle, Sp\u00e4ths Erle)',
    752: 'japonica (Japanische Erle)',
    753: 'subcordata (Kaukasische Erle)',
    754: 'rubra (Rot-Erle, Oregon-Erle)',
    755: 'hirsuta (F\u00e4rber-Erle)',
  },
  8: {
    756: 'lawsoniana (Lawsons Scheinzypresse)',
    757: 'spec. (Scheinzypresse, Art unbekannt)',
    758: 'obtusa (Hinoki-Scheinzypresse)',
    759: 'pisifera (Sawara-Scheinzypresse)',
    760: 'nootkatensis (Nutka-Scheinzypresse)',
  },
  9: {
    761: 'betulus (Gemeine Hain- oder Weissbuche)',
    762: 'betulus (Gemeine Hain- oder Weissbuche (s\u00e4ulen- oder pyramidenf\u00f6rmig))',
    763: 'caroliniana (Amerikanische Weissbuche)',
    764: "betulus (Gemeine Hain- oder Weissbuche (Carpinus betulus 'Lucas'))",
    765: 'japonica (Japanische Hainbuche)',
    766: 'spec. (Gemeine Hain- oder Weissbuche, Art unbekannt)',
    767: 'turczaninowii (Korianische Hainbuche)',
    768: 'polyneura (Hainbuche)',
    769: 'orientalis (Orientalische Hainbuche)',
    770: 'kawakamii (Hayata Hainbuche)',
  },
  10: {
    771: 'pendula (Sand-Birke, Weiss-Birke)',
    772: 'ermanii (Gold-Birke, Ermans-Birke)',
    773: 'utilis (Himalaja-Birke)',
    774: 'papyrifera (Papier-Birke)',
    775: 'alleghaniensis (Gelb-Birke)',
    776: 'albosinensis (Rote China-Birke)',
    777: 'nigra (Schwarz-Birke, Fluss-Birke)',
    778: 'spec. (Birke, Art unbekannt)',
    779: 'pendula (Karelische Birke)',
    780: 'platyphylla (Mandschurische Birke)',
    781: 'lenta (Zucker-Birke)',
    782: 'null (Sand-Birke, Weiss-Birke)',
    783: 'pubescens (Moor-Birke)',
    784: 'x caerulea (Blaue Birke (populifolia x cordifolia))',
    785: 'szechuanica (Setschuan Birke)',
    786: 'costata (Gelbe-Birke)',
    787: 'davurica (Dahurische Birke)',
    788: 'maximowicziana (Lindenbl\u00e4ttrige Birke, Bronze-Birke)',
  },
  11: {
    789: 'null (Obstbaum)',
  },
  12: {
    790: 'oblonga (Quitte-Obstgeh\u00f6lz, Sorte unbekannt)',
    791: "oblonga (Quitte-Obstgeh\u00f6lz 'Ronda')",
    792: "oblonga (Quitte-Obstgeh\u00f6lz 'Vranja')",
    793: "oblonga (Quitte-Obstgeh\u00f6lz 'Bereczki')",
    794: "oblonga (Quitte-Obstgeh\u00f6lz 'Leskovacka')",
    795: "oblonga (Quitte-Obstgeh\u00f6lz 'Wudonia')",
    796: "oblonga (Quitte-Obstgeh\u00f6lz 'Champion')",
    797: "oblonga (Quitte-Obstgeh\u00f6lz 'Cydora Robusta')",
    798: "oblonga (Quitte-Obstgeh\u00f6lz 'Konstantinopeler')",
  },
  13: {
    799: 'caprea (Sal-Weide)',
    800: 'spec. (Weide, Art unbekannt)',
    801: 'alba (Weiss-Weide, Silber-Weide)',
    802: 'viminalis (Korb-Weide, Hanf-Weide)',
    803: 'x sepulcralis (Weiss-Weide, Trauer-Weide)',
    804: 'fragilis (Bruch-Weide, Knack-Weide)',
    805: 'pentandra (Lorbeer-Weide)',
    806: 'purpurea (Purpur-Weide)',
    807: 'udensis (Amur-Weide)',
    808: 'elaeagnos (Lavendel-Weide)',
    809: 'babylonica (Chinesische Trauer-Weide (korkenzierartig))',
    810: 'x smithiana (K\u00fcbler-Weide)',
    811: 'babylonica (Chinesische Trauer-Weide)',
    812: 'rosmarinifolia (Rosmarin-Weide)',
    813: 'cinerea (Grau-Weide, Asch-Weide)',
    814: 'null (Locken-Weide)',
    815: 'daphnoides (Reif-Weide)',
    816: 'gracilistyla (Schwarzk\u00e4tzchen-Weide)',
    817: 'aurita (Ohr Weide)',
    818: 'caesia (Blaugr\u00fcne Weide)',
    819: 'myrsinifolia (Schwarze Weide)',
    820: 'appenticulata (Grosbl\u00e4ttrige Weide)',
  },
  14: {
    821: 'cordata (Winter-Linde)',
    822: 'platyphyllos (Sommer-Linde)',
    823: 'x europaea (Krim-Linde (cordata x platyphyllos))',
    824: 'spec. (Linde, Art unbekannt)',
    825: 'cordata (Winter-Linde, Stadt-Linde)',
    826: 'x europaea (Kaiser-Linde (cordata x platyphyllos))',
    827: 'tomentosa (Ungarische Silber-Linde)',
    828: 'x europaea (Holl\u00e4ndische Linde (cordata x platyphyllos))',
    829: 'henryana (Henrys-Linde)',
    830: 'x europaea (Holl\u00e4ndische Linde)',
    831: 'americana (Amerikanische Linde)',
    832: 'mongolica (Mongolische Linde)',
    833: 'x flavescens (Kegel-Linde (cordata x platyphyllos))',
    834: 'amurensis (Amur-Linde)',
    835: 'endochrysea (Chinesische Linde)',
    836: "americana (Amerikanische Linde (Tilia americana 'Redmond'))",
  },
  15: {
    837: 'abies (Rottanne, Fichte)',
    838: 'omorika (Serbische Fichte)',
    839: 'pungens (Stech-Fichte)',
    840: 'orientalis (Sapindus-Fichte, Orientalische Fichte)',
    841: 'glauca (Schimmel-Fichte, Weiss-Fichte)',
    842: 'pungens (Blau-Fichte,Stech-Fichte)',
    843: 'pungens (Zapfenfichte Lucky Strike)',
    844: 'abies (Zapfen-Fichte)',
    845: 'bicolor (Zweifarbige Fichte)',
    846: 'abies (Schleppen-Fichte)',
    847: 'spec. (Fichte, Art unbekannt)',
    848: 'breweriana (M\u00e4hnen-Fichte)',
    849: 'pungens (S) (Stech-Fichte, S\u00e4mling)',
    850: 'abies (Igel-Fichte)',
    851: 'smithiana (Himalaja-Fichte)',
    852: 'mariana (Schwarz-Fichte)',
    853: 'engelmannii (Engelmann-Fichte)',
    854: 'polita (Nadel-Fichte,Tigerschwanz-Fichte)',
  },
  16: {
    855: 'sylvestris (Gew\u00f6hnlicher Kiefer, Wald-Kiefer, F\u00f6hre)',
    856: 'nigra (Schwarz-Kiefer, \u00d6sterreichische Schwarz-Kiefer)',
    857: 'nigra (Schwarz-Kiefer)',
    858: 'wallichiana (Tr\u00e4nen-Kiefer)',
    859: 'mugo (Berg-Kiefer, Latschen-Kiefer)',
    860: 'parviflora (M\u00e4dchen-Kiefer)',
    861: 'halepensis (Aleppo-Kiefer, See-Kiefer)',
    862: 'heldreichii (Schlangenhaut-Kiefer, Bosnische Kiefer)',
    863: 'mugo (Haken-Kiefer)',
    864: 'spec. (Kiefer, Art unbekannt)',
    865: 'cembra (Zirbel-Kiefer, Arve)',
    866: 'ponderosa (Gelb-Kiefer)',
    867: 'densiflora (Japanische Rot-Kiefer)',
    868: 'pinea (Pinie)',
    869: 'jeffreyi (Jeffrey-Kiefer)',
    870: 'strobus (Weymouths-Kiefer, Strobe)',
    871: 'monticola (Westamerikanische Weymouths-Kiefer)',
    872: 'flexilis (Nevada-Zirbelkiefer)',
    873: 'aristata (Grannen-Kiefer, Fuchsschwanz-Kiefer)',
    874: 'sylvestris (Gew\u00f6hnlicher Kiefer, F\u00f6hre)',
    875: 'peuce (Mazedonische Kiefer, Rumelische Kiefer)',
    876: 'sabiniana (Weiss-Kiefer, Nuss-Kiefer)',
  },
  17: {
    877: 'platanoides (Spitz-Ahorn)',
    878: 'campestre (Feld-Ahorn, Hecken-Ahorn)',
    879: 'pseudoplatanus (Berg-Ahorn, Wald-Ahorn)',
    880: 'cappadocicum (Kolchischer Ahorn)',
    881: 'saccharinum (Silber-Ahorn)',
    882: 'rufinerve (Rostnerviger Ahorn)',
    883: 'negundo (Eschen-Ahorn)',
    884: 'palmatum (F\u00e4cher-Ahorn)',
    885: 'x freemanii (Roter Zuckerahorn)',
    886: 'platanoides (V) (Spitz-Ahorn (veredelt - gr\u00fcnbl\u00e4ttrig))',
    887: 'tataricum (Tatarischer Ahorn)',
    888: 'monspessulanum (Franz\u00f6sischer Ahorn)',
    889: 'platanoides (Spitz-Ahorn (kugelf\u00f6rmig))',
    890: 'campestre (Feld-Ahorn, Hecken-Ahorn (kugelf\u00f6rmig))',
    891: 'cissifolium (Cissus-bl\u00e4ttriger Ahorn)',
    892: 'carpinifolium (Hainbuchen-Ahorn)',
    893: 'rubrum (Rot-Ahorn)',
    894: 'saccharum (Zucker-Ahorn)',
    895: 'buergerianum (Dreizahn-Ahorn)',
    896: 'x zoeschense (Zoeschener-Ahorn)',
    897: 'griseum (Zimt-Ahorn)',
    898: 'japonicum (Eisenhutbl\u00e4ttriger Ahorn)',
    899: 'pseudoplatanus (Bergahorn)',
    900: 'spec. (Ahorn, Art unbekannt)',
    901: 'capillipes (Roter Schlangenhaut-Ahorn)',
    902: 'truncatum (Chinesischer Ahorn)',
    903: 'truncatum (Chinesischer Spitzahorn)',
    904: 'velutinum (Samt-Ahorn)',
    905: 'opalus (Italienischer-Ahorn)',
    906: 'davidii (Davids-Ahorn)',
    907: 'cappadocicum (Lobels Ahorn, Kalabrischer Spitzahorn)',
    908: 'shirasawanum (Shirasawas F\u00e4cher-Ahorn)',
    909: 'pseudoplatanus (V) (Berg-Ahorn (veredelt - gr\u00fcnbl\u00e4ttrig))',
    910: 'negundo (Eschen-Ahorn (panaschiert))',
    911: 'platanoides (Spitzahorn)',
    912: 'truncatum (Pazifischer Ahorn)',
    913: 'circinatum (Wein-Ahorn)',
    914: "rubrum (Rot-Ahorn (Acer rubrum 'Somerset'))",
    915: 'saccharum (Schwarzer Zucker-Ahorn)',
  },
  18: {
    916: 'tremula (Zitter-Pappel, Espe)',
    917: 'nigra (Pyramiden-Pappel, Italienische Pappel)',
    918: 'x canescens (Grau-Pappel (alba x tremula))',
    919: 'spec. (Pappel, Art unbekannt)',
    920: 'x canadensis (Kanadische Pappel (deltoides x nigra))',
    921: 'nigra (Schwarz-Pappel)',
    922: 'simonii (Birken-Pappel)',
    923: 'alba (Silber-Pappel, Weiss-Pappel)',
    924: 'balsamifera (Balsam-Pappel)',
    925: 'lasiocarpa (Grossblatt-Pappel)',
    926: 'balsamifera (Ontario-Pappel)',
    927: 'trichocarpa (Westliche Balsam-Pappel)',
    928: "x berolinensis (Berliner Lorbeer-Pappel (laurifolia x nigra 'Italica'))",
  },
  19: {
    929: 'null (Hybrid-Ulme)',
    930: "null (Hybrid-Ulme (Ulmus 'Fiorente'))",
    931: 'spec. (Ulme, Art unbekannt)',
    932: 'glabra (Berg-Ulme)',
    933: 'minor (Feld-Ulme)',
    934: 'laevis (Flatter-Ulme)',
    935: 'x hollandica (Holl\u00e4ndische Ulme (glabra x minor))',
    936: 'americana (Amerikanische Ulme)',
    937: 'minor (Feldulme)',
    938: 'japonica (Japanische Ulme)',
    939: "null (Hybrid-Ulme (Ulmus 'Nanguen'))",
    940: 'glabra (Berg-Ulme (h\u00e4ngende))',
  },
  20: {
    941: 'spec. (Weissdorn, Art unbekannt)',
    942: 'x lavalleei (Lederbl\u00e4ttriger Weissdorn (crus-galli x pubescens))',
    943: 'laevigata (Zweigriffliger Weissdorn)',
    944: 'monogyna (Eingriffliger Weissdorn)',
    945: 'x media (Zweigriffliger Weissdorn (laevigata x monogyna))',
    946: 'coccinea (Scharlach-Weissdorn)',
    947: 'x persimilis (Weissdorn, Hahnen-Dorn)',
    948: 'intricata (Weissdorn)',
  },
  21: {
    949: 'sylvatica (Rotbuche)',
    950: 'sylvatica (Blutbuche)',
    951: 'sylvatica (Farn-Buche)',
    952: 'spec. (Buche, Art unbekannt)',
    953: 'sylvatica (Rot-Buche, Blutbuche (h\u00e4ngende))',
    954: 'sylvatica (Blut-Buche (var. purpurea))',
    955: 'sylvatica (Rot-Buche (h\u00e4ngende))',
    956: 'orientalis (Orientalische Buche)',
    957: 'sylvatica (Rot-Buche)',
    958: 'sylvatica (Rot-Buche, Blutbuche)',
    959: 'grandifolia (Amerikanische Buche)',
    960: 'engleriana (Englers Buche)',
  },
  22: {
    961: 'alba (Weisser Maulbeerbaum)',
    962: 'nigra (Schwarzer Maulbeerbaum)',
    963: 'spec. (Maulbeerbaum, Art unbekannt)',
    964: 'kagayamae (Kagayamae Maulbeerbaum, Brombeer-Platane)',
  },
  23: {
    965: 'hippocastanum (Gemeine Rosskastanie)',
    966: 'x carnea (Rotbl\u00fchende Rosskastanie)',
    967: 'x carnea (Scharlach-Rosskastanie)',
    968: 'hippocastanum (Gef\u00fclltbl\u00fchende Rosskastanie)',
    969: 'spec. (Rosskastanie, Art unbekannt)',
    970: 'flava (Gelbe Pavie)',
    971: 'parviflora (Strauch-Kastanie)',
    972: 'turbinata (Japanische Rosskastanie)',
    973: 'x hybrida (Allegheny-Rosskastanie)',
    974: 'x neglecta (Carolina-Rosskastanie)',
    975: 'null (Gemeine Rosskastanie)',
    976: "x arnoldiana (Arnold's Rosskastanie)",
    977: 'pavia (Rote Pavie)',
    978: 'glabra (Ohio-Rosskastanie)',
    979: 'indica (Indische Rosskastanie)',
  },
  24: {
    980: 'sativa (Esskastanie-Obstgeh\u00f6lz, Sorte unbekannt)',
    981: 'sativa (S) (Esskastanie-Obstgeh\u00f6lz, S\u00e4mling)',
    982: "sativa (Esskastanie-Obstgeh\u00f6lz 'Marsol')",
    983: "sativa (Esskastanie-Obstgeh\u00f6lz 'Marron de Goujounac')",
    984: "sativa (Esskastanie-Obstgeh\u00f6lz 'Bouche de Betizac')",
    985: "sativa (Esskastanie-Obstgeh\u00f6lz 'Aguyane')",
    986: "sativa (Esskastanie-Obstgeh\u00f6lz 'Camberoune')",
    987: "sativa (Esskastanie-Obstgeh\u00f6lz 'Globosa')",
    988: "sativa (Esskastanie-Obstgeh\u00f6lz 'Nouzillard')",
    989: "sativa (Esskastanie-Obstgeh\u00f6lz 'Brunella')",
    990: "sativa (Esskastanie-Obstgeh\u00f6lz 'Arizinca')",
    991: "sativa (Esskastanie-Obstgeh\u00f6lz 'Marron de Lyon')",
    992: 'sativa (S) (Esskastanie-Obstgeh\u00f6lz, Montagne S\u00e4mling)',
    993: "pumila (Esskastanie-Obstgeh\u00f6lz 'Pumila')",
    994: "henryi (Esskastanie-Obstgeh\u00f6lz 'Henryi')",
    995: "mollissima (Esskastanie-Obstgeh\u00f6lz 'Mollissima')",
  },
  25: {
    996: 'spec. (Felsenbirne, Art unbekannt)',
    997: 'lamarckii (Kupfer-Felsenbirne)',
    998: 'arborea (Amerikanische Felsenbirne)',
    999: 'null (Kahle Felsenbirne)',
    1000: 'laevis (Kahle Felsenbirne)',
    1001: 'rotundifolia (Gemeine Felsenbirne)',
  },
  26: {
    1002: 'plicata (Riesen-Lebensbaum)',
    1003: 'occidentalis (Abendl\u00e4ndischer Lebensbaum)',
    1004: 'spec. (Lebensbaum, Art unbekannt)',
  },
  27: {
    1005: 'altissima (w) (G\u00f6tterbaum (weiblich))',
    1006: 'altissima (G\u00f6tterbaum)',
    1007: 'altissima (m) (G\u00f6tterbaum (m\u00e4nnlich))',
  },
  28: {
    1008: 'kobus (Kobushi-Magnolie, Baum-Magnolie)',
    1009: 'x soulangeana (Tulpen-Magnolie)',
    1010: 'spec. (Magnolie, Art unbekannt)',
    1011: 'denudata (Yulan-Magnolie)',
    1012: 'x loebneri (Stern-Magnolie)',
    1013: 'null (Magnolie)',
    1014: 'acuminata (Gurken-Magnolie)',
    1015: 'tripetala (Schirm-Magnolie)',
    1016: 'stellata (Magnolie)',
    1017: 'grandiflora (Immergr\u00fcne Magnolie)',
    1018: 'liliiflora (Purpur-Magnolie)',
    1019: 'null (Purpur-Magnolie)',
    1020: 'sprengeri (Sprengers Magnolie)',
  },
  29: {
    1021: 'mas (Kornelkirsche)',
    1022: 'alternifolia (Wechselbl\u00e4ttriger Hartriegel)',
    1023: 'spec. (Hartriegel, Art unbekannt)',
    1024: 'kousa (Japanischer Blumen-Hartriegel)',
    1025: 'controversa (Pagoden-Hartriegel)',
    1026: 'florida (Amerikanischer Blumen-Hartriegel)',
    1027: 'null (Nuttals Blumen-Hartriegel)',
    1028: 'nuttallii (Nuttals Blumen-Hartriegel)',
    1029: 'walteri (Wanger Hartriegel)',
    1030: 'sanguinea (Roter Hartriegel)',
  },
  30: {
    1031: 'colurna (Baumhasel)',
    1032: 'avellana (Hasel)',
    1033: 'spec. (Hasel, Art unbekannt)',
  },
  31: {
    1034: 'x hispanica (Platane (occidentalis x orientalis))',
    1035: 'spec. (Platane, Art unbekannt)',
    1036: 'orientalis (Orientalische Platane)',
  },
  32: {
    1037: 'persica (Parrotie, Eisenholzbaum)',
  },
  33: {
    1038: 'baccata (Eibe, Gew\u00f6hnliche Eibe)',
    1039: 'baccata (w) (Eibe, Gew\u00f6hnliche Eibe (weiblich))',
    1040: 'baccata (m) (Eibe, Gew\u00f6hnliche Eibe (m\u00e4nnlich))',
    1041: 'baccata (Adlerschwingen-Eibe)',
    1042: 'cuspidata (Japanische Eibe, Stachelspitzige Eibe)',
    1043: 'baccata (Gelbe Adlerschwingen-Eibe)',
    1044: "baccata (Eibe, Gew\u00f6hnliche Eibe 'Fastigiata Robusta')",
    1045: 'spec. (Eibe, Art unbekannt)',
  },
  34: {
    1046: 'spec. (Trompetenbaum, Art unbekannt)',
    1047: 'bignonioides (Trompetenbaum)',
    1048: 'speciosa (Trompetenbaum)',
    1049: 'x erubescens (Trompetenbaum)',
    1050: 'ovata (Trompetenbaum)',
  },
  35: {
    1051: 'decurrens (Kalifornische Weihrauchszeder)',
  },
  36: {
    1052: 'serrata (Japanische Zelkove)',
    1053: 'serrulata (Japanische Zelkove)',
    1054: 'carpinifolia (Kaukasus Zelkove)',
  },
  37: {
    1055: 'styraciflua (Amberbaum)',
    1056: 'spec. (Amberbaum, Art unbekannt)',
    1057: 'orientalis (Amberbaum)',
  },
  38: {
    1058: 'randaiensis (Eberesche)',
    1059: 'domestica (Speierling, Sperbe)',
    1060: 'aucuparia (Gemeine Eberesche, Vogelbeerbaum)',
    1061: 'aria (Mehlbeere)',
    1062: 'spec. (Mehlbeere, Art unbekannt)',
    1063: 'intermedia (Oxelbeere, Schwedische Mehlbeere)',
    1064: 'torminalis (Elsbeere)',
    1065: "latifolia (Rundbl\u00e4ttrige Mehlbeere (Sorbus latifolia 'Henk Vink'))",
    1066: 'mougeotii (Berg-Mehlbeere)',
    1067: 'x thuringiaca (Th\u00fcringische Eberesche)',
    1068: "domestica (Speierling 'Sossenheimer')",
    1069: 'scalaris (Leiter-Eberesche)',
    1070: 'hybrida (Bastardvogelbeere)',
    1071: 'decora (Schmuck-Eberesche, Labrador-Eberesche)',
    1072: 'megalocarpa (Mehlbeere)',
  },
  39: {
    1073: 'tulipifera (Tulpenbaum)',
    1074: 'chinense (Chinesischer Tulpenbaum)',
  },
  40: {
    1075: 'carpinifolia (Gew\u00f6hnliche Hopfenbuche)',
    1076: 'virginiana (Virginische Hopfenbuche)',
    1077: 'japonica (Japanische Hopfenbuche)',
  },
  41: {
    1078: 'pseudoacacia (Robinie, Schein-Akazie)',
    1079: 'x ambigua (Robinie, Schein-Akazie)',
    1080: 'spec. (Robinie, Art unbekannt)',
    1081: 'pseudoacacia (Robinie)',
    1082: 'viscosa (Robinie, Klebrige Robinie)',
  },
  42: {
    1083: 'aquifolium (Stechpalme)',
    1084: 'aquifolium (w) (Stechpalme (weiblich))',
    1085: 'aquifolium (m) (Stechpalme (m\u00e4nnlich))',
  },
  43: {
    1086: 'tomentosa (Blauglockenbaum)',
    1087: 'spec. (Blauglockenbaum, Art unbekannt)',
  },
  44: {
    1088: 'spec. (Dattelpflaume, Art unbekannt)',
    1089: 'virginiana (Dattelpflaume, Perisimone)',
    1090: 'lotus (Dattelpflaume, Lotuspflanze)',
    1091: 'kaki (Dattelpflaume, Kaki)',
    1092: 'kaki (w) (Dattelpflaume, Kaki (weiblich))',
  },
  45: {
    1093: 'spec. (Aralie, Art unbekannt)',
    1094: 'elata (Aralie)',
  },
  46: {
    1095: 'fraxinifolia (Kaukasische Fl\u00fcgelnuss)',
    1096: 'rhoifolia (Japanische Fl\u00fcgelnuss)',
    1097: 'stenoptera (Chinesische Fl\u00fcgelnuss)',
    1098: 'spec. (Fl\u00fcgelnuss, Art unbekannt)',
    1099: 'x rehderiana (Rehders Fl\u00fcgelnuss)',
  },
  47: {
    1100: 'australis (S\u00fcdlicher Z\u00fcrgelbaum)',
    1101: 'occidentalis (Amerikanischer Z\u00fcrgelbaum)',
    1102: 'spec. (Z\u00fcrgelbaum, Art unbekannt)',
    1103: 'mississipiensis (Glattbl\u00e4ttriger Z\u00fcrgelbaum)',
  },
  48: {
    1104: 'triacanthos (Dornenlose Gleditschie)',
    1105: 'triacanthos (Gleditschie, Lederh\u00fclsenbaum)',
    1106: 'spec. (Gleditschie, Lederh\u00fclsenbaum, Art unbekannt)',
  },
  49: {
    1107: 'decidua (Europ\u00e4ische L\u00e4rche)',
    1108: 'x marschlinsii (Hybridl\u00e4rche (decidua x kaempferi))',
    1109: 'kaempferi (Japanische L\u00e4rche)',
    1110: 'spec. (L\u00e4rche, Art unbekannt)',
  },
  50: {
    1111: 'japonica (Japanischer Schnurbaum)',
    1112: 'spec. (Schnurbaum, Art unbekannt)',
  },
  51: {
    1113: 'kentukea (Gelbholz)',
    1114: 'lutea (Amerikanisches Gelbholz)',
  },
  52: {
    1115: 'nigra (Schwarzer Holunder)',
  },
  53: {
    1116: 'null (Laubbaum)',
  },
  54: {
    1117: 'japonicum (Kuchenbaum, Katsurabaum)',
  },
  55: {
    1118: 'canadensis (Kanadische Hemlocktanne, Schirlingstanne)',
    1119: 'heterophylla (Westliche Hemlocktanne)',
    1120: 'diversifolia (Japanische Hemlocktanne)',
    1121: 'spec. (Hemlocktanne, Art unbekannt)',
  },
  56: {
    1122: 'siliquastrum (Gew\u00f6hnlicher Judasbaum)',
    1123: 'canadensis (Kanadischer Judasbaum)',
  },
  57: {
    1124: 'dioica (Geweihbaum)',
    1125: 'dioica (m) (Geweihbaum (m\u00e4nnlich))',
  },
  58: {
    1126: 'libani (Atlas-Zeder)',
    1127: 'deodara (Himalaja-Zeder)',
    1128: 'libani (Libanon-Zeder)',
  },
  59: {
    1129: 'pomifera (Milchorange, Osagedorn)',
  },
  60: {
    1130: 'coggygria (Per\u00fcckenstrauch)',
  },
  61: {
    1131: 'alba (Weiss-Tanne, Edel-Tanne)',
    1132: 'nordmanniana (Nordmanns-Tanne)',
    1133: 'cephalonica (Griechische Tanne)',
    1134: 'bracteata (Grannen-Tanne)',
    1135: 'koreana (Korea-Tanne, Zapfen-Tanne (Veredlung))',
    1136: 'spec. (Tanne, Art unbekannt)',
    1137: 'concolor (Kolorado-Tanne, Grau-Tanne)',
    1138: 'nordmanniana subsp. equi-trojani (Nordmanns-Tanne, Troja-Tanne)',
    1139: 'lasiocarpa (Felsengebirgs-Tanne)',
    1140: 'procera (Edel-Tanne, Silber-Tanne)',
    1141: 'koreana (Korea-Tanne, Zapfen-Tanne)',
    1142: 'pinsapo (Spanische Tanne)',
    1143: 'grandis (K\u00fcsten-Tanne, Riesen-Tanne)',
    1144: 'amabilis (Purpur-Tanne)',
  },
  62: {
    1145: 'simulans (T\u00e4uschende Stachelesche)',
    1146: 'piperitum (Sichuan-Peffer)',
  },
  63: {
    1147: 'menziesii (Douglasie, Douglasfichte)',
  },
  64: {
    1148: 'biloba (Ginkgo, M\u00e4dchenhaarbaum, F\u00e4cherblattbaum)',
    1149: 'biloba (m) (Ginkgo, M\u00e4dchenhaarbaum, F\u00e4cherblattbaum (m\u00e4nnlich))',
    1150: 'biloba (w) (Ginkgo, M\u00e4dchenhaarbaum, F\u00e4cherblattbaum (weiblich))',
  },
  65: {
    1151: 'x watereri (Goldregen)',
    1152: 'anagyroides (Gemeiner Goldregen)',
    1153: 'spec. (Goldregen, Art unbekannt)',
  },
  66: {
    1154: 'carica (Feige)',
    1155: 'carica (Feige - Quinto)',
    1156: 'carica (Feige - Violletta)',
  },
  67: {
    1157: 'giganteum (Mammutbaum, Riesensequoia)',
    1158: 'giganteum (Mammutbaum, Riesensequoia, h\u00e4ngend)',
  },
  68: {
    1159: 'dolabrata (Hiba-Lebensbaum)',
  },
  69: {
    1160: 'harringtonii (Kopfeibe)',
    1161: 'harringtonii (Kopfeibe (s\u00e4ulenform))',
    1162: 'fortunei (Kopfeibe)',
  },
  70: {
    1163: 'sempervirens (Buchsbaum)',
  },
  71: {
    1164: 'glyptostroboides (Urwelt-Mammutbaum)',
  },
  72: {
    1165: 'involucrata (Taubenbaum, Taschentuchbaum)',
  },
  73: {
    1166: 'daniellii (Stinkesche)',
    1167: 'spec. (Stinkesche, Art unbekannt)',
  },
  74: {
    1168: 'angustifolia (\u00d6lweide)',
  },
  75: {
    1169: 'paniculata (Blasenbaum, Blasenesche)',
    1170: 'spec. (Blasenbaum, Blasenesche, Art unbekannt)',
  },
  76: {
    1171: 'sinensis (Chinesischer Surenbaum)',
  },
  77: {
    1172: 'communis (Schwedischer Wacholder)',
    1173: 'communis (Gemeiner Wacholder)',
    1174: 'scopulorum (Felsengebirgs-Wacholder)',
    1175: 'virginiana (Zypressen-Wacholder)',
    1176: 'virginiana (Chinesischer Wacholder)',
    1177: 'spec. (Wacholder, Art unbekannt)',
  },
  78: {
    1178: 'distichum (Sumpfzypresse)',
  },
  79: {
    1179: 'sylvatica (Tupelobaum)',
  },
  80: {
    1180: 'cathartica (Echter Kreuzdorn (Purgierkreuzdorn))',
  },
  81: {
    1181: 'alnus (Faulbaum (Pulverholz))',
  },
  82: {
    1182: 'germanica (Mispel)',
  },
  83: {
    1183: 'amurense (Amur-Korkbaum, Echter Korkbaum)',
    1184: 'japonicum (Japanischer Korkbaum)',
  },
  84: {
    1185: 'cordiformis (Bitternuss)',
    1186: 'ovata (Schuppenrinden-Hickory)',
    1187: 'illinoinensis (Pecannuss)',
  },
  85: {
    1188: 'japonica (Japanische Sicheltanne)',
  },
  86: {
    1189: 'europaeus (Pfaffenh\u00fctchen)',
  },
  87: {
    1190: 'macrocarpa (Monterey-Zypresse)',
    1191: 'sempervirens (Mittelmeer-Zypresse)',
    1192: 'arizonica (Arizona-Zypresse)',
    1193: 'spec. (Zypresse, Art unbekannt)',
    1194: 'arizonica (Glatte Arizona-Zypresse)',
  },
  88: {
    1195: 'sempervirens (K\u00fcsten-Mammutbaum, Redwood)',
  },
  89: {
    1196: 'sinensis (Scheinfeige)',
  },
  90: {
    1197: 'semidecidua (Sycoparrotie / Gattungshybride (Parrotia x Sycopsis))',
  },
  91: {
    1198: 'antarctica (Scheinbuche)',
  },
  92: {
    1199: 'trifoliata (Lederstrauch, Kleeulme)',
  },
  93: {
    1200: 'polycarpa (Orangenkirsche)',
  },
  94: {
    1201: 'tetranda (Tamariske)',
  },
  95: {
    1202: 'simplex (Sonnenschirmbaum, Chinesischer Parasolbaum)',
  },
  96: {
    1203: 'decorus (Stattliche Duftbl\u00fcte)',
  },
  97: {
    1204: 'ulmoides (Guttaperchabaum)',
  },
  98: {
    1205: 'trifoliata (Bitterorange)',
  },
  99: {
    1206: 'papyrifera (Papiermaulbeerbaum)',
  },
  100: {
    1207: 'verticillata (Japanische Schirmtanne)',
  },
  101: {
    1208: 'triloba (Indianerbanane, Dreilappige Papau)',
  },
  102: {
    1209: 'strobilacea (Zapfennuss)',
  },
  103: {
    1210: 'sinense (Chinesischer Liguster)',
  },
  104: {
    1211: 'orientalis (Morgenl\u00e4ndischer Lebensbaum, F\u00e4cherlebensbaum)',
  },
  105: {
    1212: 'null (Geh\u00f6lz (Laub oder Nadel))',
  },
  106: {
    1213: 'x fraseri (Glanzmispel)',
  },
  107: {
    1214: 'typhina (Schlitzbl\u00e4ttriger Essigbaum)',
  },
  108: {
    1215: 'praecox (Chinesische Winterbl\u00fcte)',
  },
  109: {
    1216: 'retusus (Chinesischer Schneeflockenstrauch)',
  },
  110: {
    1217: 'julibrissin (Schlafbaum, Seidenakazie)',
  },
  111: {
    1218: 'discolor (Wald-Schaumspiere)',
  },
  112: {
    1219: 'japonica (Japanische Mispel)',
  },
  113: {
    1220: 'araucana (Schmuck-Tanne, Chilenische Araukarie)',
  },
  114: {
    1221: 'maackii (Schirm-Heckenkirsche)',
  },
  115: {
    1222: 'pseudocamellia (Japanische Scheinkamelie)',
  },
  116: {
    1223: 'amurensis (Amur-Maackia)',
  },
  117: {
    1224: 'lanceolata (Spiesstanne)',
  },
  118: {
    1225: 'tashkentensis (Baumoleander, schmalbl\u00e4ttriger Trompetenbaum)',
  },
  119: {
    1226: 'californica (Nusseibe)',
    1227: 'nucifera (Japanische Nusseibe)',
  },
  120: {
    1228: 'polyandra (Vielm\u00e4nnige Sch\u00f6nulme)',
  },
  121: {
    1229: 'europaea (\u00d6lbaum, Olive)',
  },
  122: {
    1230: 'hispida (Fl\u00fcgelstorax)',
  },
  123: {
    1231: 'leylandii (Leylandzypresse)',
  },
};
