// English common names for tree genera, keyed by the Latin genus name used in
// the Baumkataster (baumgattunglat). Mirrors GenusDeNames.js. Genera not listed
// here fall back to showing the Latin name only. In English mode, species stay
// in Latin (we only translate the genus), so this file plus the Latin epithet
// gives e.g. "Oak (Quercus)" for the genus and "Quercus robur" for the species.
export const GenusEnNames = {
  Malus: 'Apple',
  Pyrus: 'Pear',
  Juglans: 'Walnut',
  Prunus: 'Cherry/Plum',
  Quercus: 'Oak',
  Fraxinus: 'Ash',
  Alnus: 'Alder',
  Chamaecyparis: 'False cypress',
  Carpinus: 'Hornbeam',
  Betula: 'Birch',
  Cydonia: 'Quince',
  Salix: 'Willow',
  Tilia: 'Linden',
  Picea: 'Spruce',
  Pinus: 'Pine',
  Acer: 'Maple',
  Populus: 'Poplar',
  Ulmus: 'Elm',
  Crataegus: 'Hawthorn',
  Fagus: 'Beech',
  Morus: 'Mulberry',
  Aesculus: 'Horse chestnut',
  Castanea: 'Sweet chestnut',
  Amelanchier: 'Serviceberry',
  Thuja: 'Arborvitae',
  Ailanthus: 'Tree of heaven',
  Magnolia: 'Magnolia',
  Cornus: 'Dogwood',
  Corylus: 'Hazel',
  Platanus: 'Plane',
  Parrotia: 'Persian ironwood',
  Taxus: 'Yew',
  Catalpa: 'Catalpa',
  Calocedrus: 'Incense cedar',
  Zelkova: 'Zelkova',
  Liquidambar: 'Sweetgum',
  Sorbus: 'Whitebeam/Rowan',
  Liriodendron: 'Tulip tree',
  Ostrya: 'Hop hornbeam',
  Robinia: 'Black locust',
  Ilex: 'Holly',
  Paulownia: 'Foxglove tree',
  Diospyros: 'Persimmon',
  Pterocarya: 'Wingnut',
  Celtis: 'Hackberry',
  Gleditsia: 'Honey locust',
  Larix: 'Larch',
  Sophora: 'Pagoda tree',
  Cladrastis: 'Yellowwood',
  Sambucus: 'Elder',
  Cercidiphyllum: 'Katsura',
  Tsuga: 'Hemlock',
  Cercis: 'Redbud',
  Gymnocladus: 'Kentucky coffeetree',
  Cedrus: 'Cedar',
  Cotinus: 'Smoke tree',
  Abies: 'Fir',
  Pseudotsuga: 'Douglas fir',
  Ficus: 'Fig',
  Laburnum: 'Golden chain',
  Sequoiadendron: 'Giant sequoia',
  Metasequoia: 'Dawn redwood',
  Buxus: 'Boxwood',
  Davidia: 'Dove tree',
  Elaeagnus: 'Oleaster',
  Koelreuteria: 'Golden rain tree',
  Juniperus: 'Juniper',
  Taxodium: 'Bald cypress',
  Nyssa: 'Tupelo',
  Rhamnus: 'Buckthorn',
  Frangula: 'Alder buckthorn',
  Mespilus: 'Medlar',
  Phellodendron: 'Cork tree',
  Carya: 'Hickory',
  Cryptomeria: 'Japanese cedar',
  Euonymus: 'Spindle',
  Cupressus: 'Cypress',
  Sequoia: 'Coast redwood',
  Nothofagus: 'Southern beech',
  Tamarix: 'Tamarisk',
  Osmanthus: 'Tea olive',
  Eucommia: 'Hardy rubber tree',
  Poncirus: 'Trifoliate orange',
  Broussonetia: 'Paper mulberry',
  Ligustrum: 'Privet',
  Photinia: 'Photinia',
  Rhus: 'Sumac',
  Chionanthus: 'Fringe tree',
  Albizia: 'Silk tree',
  Eriobotrya: 'Loquat',
  Araucaria: 'Monkey puzzle',
  Lonicera: 'Honeysuckle',
  Stewartia: 'Stewartia',
  Cunninghamia: 'China fir',
  Torreya: 'Nutmeg yew',
  Olea: 'Olive',
  Ginkgo: 'Ginkgo',
  Sciadopitys: 'Umbrella pine',
  Cephalotaxus: 'Plum yew',
  Maclura: 'Osage orange',
  Tetradium: 'Bee bee tree',
  Asimina: 'Pawpaw',
};
