// One notable world event per planting year that appears in the data. Compiled
// from general historical knowledge; the popup also links to the German
// Wikipedia article for that year so readers can dig deeper. Years without an
// entry simply show no event line.
export const yearEvents = {
  1665: 'Grosse Pest in London; Newton legt die Grundlagen der Gravitationstheorie',
  1780: 'Tod von Kaiserin Maria Theresia',
  1796: 'Napoleons Italienfeldzug beginnt',
  1800: 'Alessandro Volta stellt die erste Batterie vor',
  1805: 'Seeschlacht von Trafalgar; Schlacht bei Austerlitz',
  1806: 'Ende des Heiligen Römischen Reiches',
  1815: 'Napoleons Niederlage bei Waterloo; Wiener Kongress',
  1820: 'Erste Sichtung des antarktischen Kontinents',
  1822: 'Champollion entschlüsselt die ägyptischen Hieroglyphen',
  1826: 'Die älteste erhaltene Fotografie entsteht',
  1831: 'Charles Darwin sticht mit der HMS Beagle in See',
  1832: 'Tod von Johann Wolfgang von Goethe',
  1836: 'Schlacht von Alamo in Texas',
  1845: 'Beginn der grossen Hungersnot in Irland',
  1850: 'Kalifornien wird US-Bundesstaat (Goldrausch)',
  1852: 'Napoleon III. begründet das Zweite Kaiserreich in Frankreich',
  1856: 'Ende des Krimkriegs',
  1859: 'Darwin veröffentlicht „Über die Entstehung der Arten“',
  1860: 'Abraham Lincoln wird zum US-Präsidenten gewählt',
  1864: 'Gründung des Roten Kreuzes in Genf (Genfer Konvention)',
  1865: 'Ende des Amerikanischen Bürgerkriegs; Lincoln wird ermordet',
  1866: 'Das erste dauerhafte Transatlantik-Telegrafenkabel wird verlegt',
  1868: 'Meiji-Restauration in Japan',
  1870: 'Beginn des Deutsch-Französischen Krieges',
  1874: 'Erste Impressionisten-Ausstellung in Paris',
  1875: 'Die internationale Meterkonvention wird unterzeichnet',
  1876: 'Alexander Graham Bell meldet das Telefon zum Patent an',
  1880: 'Vollendung des Kölner Doms',
  1882: 'Robert Koch entdeckt den Tuberkulose-Erreger',
  1885: 'Carl Benz baut das erste Automobil',
  1886: 'Die Freiheitsstatue wird in New York errichtet',
  1888: 'Kodak bringt die erste einfache Rollfilmkamera heraus',
  1889: 'Der Eiffelturm wird zur Pariser Weltausstellung eröffnet',
  1890: 'Tod von Vincent van Gogh',
  1895: 'Die Brüder Lumière führen den ersten Film vor; Röntgen entdeckt die X-Strahlen',
  1896: 'Erste Olympische Spiele der Neuzeit in Athen',
  1897: 'Erster Zionistenkongress in Basel',
  1900: 'Max Planck begründet die Quantentheorie',
  1901: 'Tod von Königin Victoria; erste Nobelpreise verliehen',
  1902: 'Verheerender Ausbruch des Vulkans Mont Pelé',
  1904: 'Beginn des Russisch-Japanischen Krieges',
  1905: 'Einsteins „Wunderjahr“ – u. a. die spezielle Relativitätstheorie',
  1906: 'Schweres Erdbeben zerstört San Francisco',
  1907: 'Picasso malt „Les Demoiselles d’Avignon“ – Beginn des Kubismus',
  1908: 'Tunguska-Ereignis in Sibirien; Ford bringt das Modell T heraus',
  1910: 'Beginn der Mexikanischen Revolution',
  1911: 'Roald Amundsen erreicht als Erster den Südpol',
  1912: 'Untergang der Titanic',
  1915: 'Einstein vollendet die Allgemeine Relativitätstheorie',
  1916: 'Schlachten von Verdun und an der Somme',
  1917: 'Oktoberrevolution in Russland; USA treten in den Krieg ein',
  1918: 'Ende des Ersten Weltkriegs; Beginn der Spanischen Grippe',
  1920: 'Gründung des Völkerbunds mit Sitz in Genf',
  1921: 'Einstein erhält den Physik-Nobelpreis',
  1922: 'Entdeckung des Grabes von Tutanchamun; Gründung der Sowjetunion',
  1923: 'Hyperinflation in Deutschland',
  1924: 'Tod von Lenin; erste Olympische Winterspiele in Chamonix',
  1925: 'John Logie Baird führt erstmals das Fernsehen vor',
  1926: 'Deutschland tritt dem Völkerbund bei',
  1928: 'Alexander Fleming entdeckt das Penicillin',
  1930: 'Gandhis Salzmarsch; Entdeckung des Pluto',
  1931: 'Eröffnung des Empire State Building',
  1932: 'Entdeckung des Neutrons',
  1934: 'Der „Lange Marsch“ der chinesischen Kommunisten beginnt',
  1935: 'Persien wird offiziell in Iran umbenannt',
  1936: 'Olympische Spiele in Berlin; Beginn des Spanischen Bürgerkriegs',
  1937: 'Hindenburg-Katastrophe; Picasso malt „Guernica“',
  1938: 'Otto Hahn gelingt die Kernspaltung',
  1939: 'Beginn des Zweiten Weltkriegs',
  1940: 'Luftschlacht um England',
  1941: 'Angriff auf Pearl Harbor; USA treten in den Krieg ein',
  1942: 'Erste kontrollierte nukleare Kettenreaktion (Enrico Fermi)',
  1943: 'Kriegswende bei Stalingrad',
  1944: 'D-Day: Landung der Alliierten in der Normandie',
  1945: 'Ende des Zweiten Weltkriegs; Atombomben auf Japan; Gründung der UNO',
  1946: 'Der erste programmierbare Grossrechner ENIAC wird vorgestellt',
  1948: 'Gründung des Staates Israel; Allgemeine Erklärung der Menschenrechte',
  1950: 'Beginn des Koreakriegs',
  1951: 'Erste landesweite Farbfernseh-Sendung in den USA',
  1952: 'Elisabeth II. wird Königin; erste Wasserstoffbombe gezündet',
  1953: 'Aufklärung der DNA-Doppelhelix; Erstbesteigung des Mount Everest',
  1954: '„Wunder von Bern“ – Deutschland wird Fussball-Weltmeister',
  1955: 'Tod von Albert Einstein',
  1956: 'Suezkrise und Ungarn-Aufstand',
  1957: 'Sputnik 1 – Beginn des Weltraumzeitalters',
  1958: 'Gründung der NASA',
  1959: 'Sieg der Kubanischen Revolution',
  1960: '„Afrikanisches Jahr“: 17 Staaten werden unabhängig',
  1961: 'Juri Gagarin fliegt als erster Mensch ins All; Bau der Berliner Mauer',
  1962: 'Kubakrise bringt die Welt an den Rand eines Atomkriegs',
  1963: 'Ermordung von John F. Kennedy; Kings „I Have a Dream“',
  1964: 'Nelson Mandela wird zu lebenslanger Haft verurteilt',
  1965: 'Erster Weltraumspaziergang',
  1966: 'Beginn der Kulturrevolution in China',
  1967: 'Erste Herztransplantation durch Christiaan Barnard',
  1968: 'Prager Frühling und weltweite Proteste',
  1969: 'Erste Mondlandung (Apollo 11); Woodstock-Festival',
  1970: 'Erster „Earth Day“ – die Umweltbewegung erstarkt',
  1971: 'Gründung von Greenpeace',
  1972: '„Pong“ startet das Zeitalter der Videospiele',
  1973: 'Ölkrise erschüttert die Weltwirtschaft',
  1974: 'Rücktritt von US-Präsident Nixon (Watergate)',
  1975: 'Ende des Vietnamkriegs',
  1976: 'Apple wird gegründet',
  1977: 'Start der Voyager-Raumsonden; Tod von Elvis Presley',
  1978: 'Geburt des ersten „Retortenbabys“',
  1979: 'Islamische Revolution im Iran',
  1980: 'Die WHO erklärt die Pocken für ausgerottet',
  1981: 'Erster Space-Shuttle-Flug; AIDS wird erstmals beschrieben',
  1982: 'Die Audio-CD kommt auf den Markt',
  1983: 'Das Internet (TCP/IP) nimmt offiziell den Betrieb auf',
  1984: 'Apple stellt den Macintosh vor',
  1985: 'Das Ozonloch über der Antarktis wird entdeckt',
  1986: 'Reaktorkatastrophe von Tschernobyl',
  1987: 'Montreal-Protokoll zum Schutz der Ozonschicht',
  1988: 'Ende des Iran-Irak-Kriegs',
  1989: 'Fall der Berliner Mauer',
  1990: 'Deutsche Wiedervereinigung; Freilassung von Nelson Mandela',
  1991: 'Ende der Sowjetunion; das World Wide Web wird öffentlich',
  1992: 'Erdgipfel von Rio – Klimaschutz wird Weltthema',
  1993: 'Gründung der Europäischen Union',
  1994: 'Ende der Apartheid – Mandela wird Präsident; Völkermord in Ruanda',
  1995: 'Erster Exoplanet entdeckt (Genfer Astronomen); Windows 95 erscheint',
  1996: 'Das Klonschaf „Dolly“ wird geboren',
  1997: 'Tod von Prinzessin Diana; der erste „Harry Potter“ erscheint',
  1998: 'Google wird gegründet',
  1999: 'Der Euro wird als Buchgeld eingeführt',
  2000: 'Weltweite Jahrtausendwende (Y2K)',
  2001: 'Terroranschläge des 11. September; Wikipedia geht online',
  2002: 'Das Euro-Bargeld kommt in Umlauf',
  2003: 'Beginn des Irakkriegs; Columbia-Shuttle verunglückt',
  2004: 'Tsunami im Indischen Ozean; Facebook startet',
  2005: 'YouTube wird gegründet',
  2006: 'Pluto wird zum Zwergplaneten herabgestuft',
  2007: 'Apple stellt das erste iPhone vor',
  2008: 'Globale Finanzkrise',
  2009: 'Barack Obama wird US-Präsident',
  2010: 'Ölkatastrophe „Deepwater Horizon“ im Golf von Mexiko',
  2011: 'Reaktorkatastrophe von Fukushima; Arabischer Frühling',
  2012: 'Nachweis des Higgs-Bosons am CERN bei Genf',
  2013: 'Wahl von Papst Franziskus',
  2014: 'Russland annektiert die Krim',
  2015: 'Pariser Klimaabkommen; europäische Flüchtlingskrise',
  2016: 'Brexit-Referendum; Wahl von Donald Trump',
  2017: 'Die #MeToo-Bewegung breitet sich weltweit aus',
  2018: 'Greta Thunberg startet den Klima-Schulstreik',
  2019: 'Erstes Foto eines Schwarzen Lochs',
  2020: 'Beginn der COVID-19-Pandemie',
  2021: 'Sturm aufs US-Kapitol; erster Helikopterflug auf dem Mars',
  2022: 'Russischer Angriff auf die Ukraine; erste Bilder des James-Webb-Teleskops',
  2023: 'ChatGPT löst den weltweiten KI-Boom aus',
  2024: 'Olympische Sommerspiele in Paris',
  2025: 'Einer der jüngsten Bäume im Baumkataster',
  2026: 'Frisch gepflanzt – einer von Zürichs neuesten Stadtbäumen',
};
